import type { EmptyBehavior, MetricDefinition, MetricValue } from "./types";
import { USER_ROLES, type UserRole } from "../roleMenu";

const ALL = USER_ROLES;
const CRM = ["super_admin", "admin", "manager", "crm"] as const satisfies readonly UserRole[];
const MANAGERS = ["super_admin", "admin", "manager"] as const satisfies readonly UserRole[];
const PEOPLE = ["super_admin", "admin", "manager", "hr"] as const satisfies readonly UserRole[];

const metric = (definition: MetricDefinition) => definition;
export const METRIC_CATALOG: readonly MetricDefinition[] = [
  metric({ key:"tasks_assigned",displayName:"Tasks assigned",definition:"Distinct tasks assigned in the selected local date window.",numerator:null,denominator:null,roles:ALL,sourceModule:"tasks",dateWindow:"Assignment is included when its effective planned date is inside the range.",scope:"Own work for regular roles; authorized branch, department, or tenant scope for elevated roles.",emptyBehavior:"zero",format:"count",comparable:true }),
  metric({ key:"tasks_completed",displayName:"Tasks completed",definition:"Distinct assigned tasks completed in the selected local date window.",numerator:null,denominator:null,roles:ALL,sourceModule:"tasks",dateWindow:"actual_datetime is inside the range.",scope:"Same as tasks assigned.",emptyBehavior:"zero",format:"count",comparable:true }),
  metric({ key:"task_completion_rate",displayName:"Completion rate",definition:"Completed assigned tasks divided by assigned tasks in the selected range.",numerator:"tasks_completed",denominator:"tasks_assigned",roles:ALL,sourceModule:"tasks",dateWindow:"Uses the same selected range for numerator and denominator.",scope:"Same as tasks assigned.",emptyBehavior:"no_data",format:"percentage",comparable:true }),
  metric({ key:"on_time_completed",displayName:"On-time completed",definition:"Completed tasks whose actual completion time is not after the effective due time.",numerator:null,denominator:null,roles:ALL,sourceModule:"tasks",dateWindow:"actual_datetime is inside the range.",scope:"Same as tasks assigned.",emptyBehavior:"zero",format:"count",comparable:true }),
  metric({ key:"overdue_open",displayName:"Overdue open",definition:"Open tasks whose effective due time is before the report cutoff.",numerator:null,denominator:null,roles:ALL,sourceModule:"tasks",dateWindow:"Open-state snapshot at query time; never presented as historical as-of state.",scope:"Same as tasks assigned.",emptyBehavior:"zero",format:"count",comparable:false }),
  metric({ key:"average_completion_delay",displayName:"Average completion delay",definition:"Average positive delay in minutes across completed tasks; early completions contribute zero.",numerator:"sum of positive delay minutes",denominator:"completed tasks with a due and completion time",roles:ALL,sourceModule:"tasks",dateWindow:"actual_datetime is inside the range.",scope:"Same as tasks assigned.",emptyBehavior:"not_applicable",format:"duration_minutes",comparable:true }),
  metric({ key:"checklist_completion",displayName:"Checklist completion",definition:"Completed required checklist items divided by required checklist items on scoped tasks.",numerator:"completed required checklist items",denominator:"required checklist items",roles:ALL,sourceModule:"tasks",dateWindow:"Checklist items attached to tasks planned in the range.",scope:"Same as tasks assigned.",emptyBehavior:"not_applicable",format:"percentage",comparable:true }),
  metric({ key:"active_fms_stages",displayName:"Active FMS stages",definition:"FMS stages currently in progress and assigned within authorized scope.",numerator:null,denominator:null,roles:ALL,sourceModule:"fms",dateWindow:"Current operational state; date range does not reconstruct past state.",scope:"Own assigned stages for regular roles; authorized aggregate scope for elevated roles.",emptyBehavior:"zero",format:"count",comparable:false }),
  metric({ key:"completed_fms_stages",displayName:"Completed FMS stages",definition:"FMS stages completed during the selected range.",numerator:null,denominator:null,roles:ALL,sourceModule:"fms",dateWindow:"actual_datetime is inside the range.",scope:"Authorized FMS scope.",emptyBehavior:"zero",format:"count",comparable:true }),
  metric({ key:"fms_sla_breaches",displayName:"FMS SLA breaches",definition:"Scoped FMS stages marked breached or completed after their planned time.",numerator:null,denominator:null,roles:ALL,sourceModule:"fms",dateWindow:"Completion or effective planned date intersects the selected range.",scope:"Authorized FMS scope.",emptyBehavior:"zero",format:"count",comparable:true }),
  metric({ key:"forms_submitted",displayName:"Forms submitted",definition:"Authorized form submissions created in the selected range.",numerator:null,denominator:null,roles:ALL,sourceModule:"forms",dateWindow:"submitted_at is inside the range.",scope:"Own submissions or authorized managerial scope.",emptyBehavior:"zero",format:"count",comparable:true }),
  metric({ key:"forms_awaiting_submission",displayName:"Awaiting submission",definition:"Active assigned task links requiring a form that has no matching submission by the assigned user.",numerator:null,denominator:null,roles:ALL,sourceModule:"forms",dateWindow:"Current open task state; not historical.",scope:"Own actionable task links or authorized aggregate scope.",emptyBehavior:"zero",format:"count",comparable:false }),
  metric({ key:"crm_followups_due",displayName:"Follow-ups due",definition:"Authorized open CRM follow-ups due in the selected range.",numerator:null,denominator:null,roles:CRM,sourceModule:"crm",dateWindow:"due_date is inside the range.",scope:"CRM assignment and branch rules are enforced by PostgreSQL.",emptyBehavior:"zero",format:"count",comparable:true }),
  metric({ key:"crm_followups_overdue",displayName:"Follow-ups overdue",definition:"Authorized open CRM follow-ups due before the selected range end.",numerator:null,denominator:null,roles:CRM,sourceModule:"crm",dateWindow:"Current open state at query time.",scope:"CRM assignment and branch rules are enforced by PostgreSQL.",emptyBehavior:"zero",format:"count",comparable:false }),
  metric({ key:"crm_followups_completed",displayName:"Follow-ups completed",definition:"Authorized CRM follow-ups completed in the selected range.",numerator:null,denominator:null,roles:CRM,sourceModule:"crm",dateWindow:"completed_at is inside the range.",scope:"CRM assignment and branch rules are enforced by PostgreSQL.",emptyBehavior:"zero",format:"count",comparable:true }),
  metric({ key:"unread_notifications",displayName:"Unread notifications",definition:"Unread in-app notifications for the current user.",numerator:null,denominator:null,roles:ALL,sourceModule:"notifications",dateWindow:"Current state; independent of the analytics date range.",scope:"Current user only.",emptyBehavior:"zero",format:"count",comparable:false }),
  metric({ key:"active_people",displayName:"Active people",definition:"Profiles with active working status and enabled login in authorized organization scope.",numerator:null,denominator:null,roles:PEOPLE,sourceModule:"people",dateWindow:"Current state only.",scope:"Tenant for admins; own branch for managers; authorized people scope for HR.",emptyBehavior:"zero",format:"count",comparable:false }),
  metric({ key:"people_available",displayName:"People available",definition:"Active people recorded present, half-day, or remote for the tenant-local current date.",numerator:null,denominator:null,roles:PEOPLE,sourceModule:"people",dateWindow:"Tenant-local current date only.",scope:"Authorized people scope.",emptyBehavior:"zero",format:"count",comparable:false }),
  metric({ key:"people_availability_rate",displayName:"Availability",definition:"Available active people divided by active people in the same scope.",numerator:"people_available",denominator:"active_people",roles:PEOPLE,sourceModule:"people",dateWindow:"Tenant-local current date only.",scope:"Authorized people scope.",emptyBehavior:"no_data",format:"percentage",comparable:false }),
  metric({ key:"fms_instances_active",displayName:"Active FMS instances",definition:"FMS instances currently active in authorized scope.",numerator:null,denominator:null,roles:MANAGERS,sourceModule:"fms",dateWindow:"Current state only.",scope:"Authorized tenant or branch scope.",emptyBehavior:"zero",format:"count",comparable:false }),
  metric({ key:"form_reviews_pending",displayName:"Form reviews pending",definition:"Authorized submitted forms awaiting review.",numerator:null,denominator:null,roles:MANAGERS,sourceModule:"forms",dateWindow:"Current state only.",scope:"Authorized tenant or branch scope.",emptyBehavior:"zero",format:"count",comparable:false }),
  metric({ key:"crm_clients",displayName:"CRM clients",definition:"Non-merged CRM client records in authorized scope.",numerator:null,denominator:null,roles:CRM,sourceModule:"crm",dateWindow:"Current state only.",scope:"PostgreSQL CRM scope.",emptyBehavior:"zero",format:"count",comparable:false }),
  metric({ key:"crm_walkins",displayName:"CRM walk-ins",definition:"Authorized walk-in visits recorded in the selected range.",numerator:null,denominator:null,roles:CRM,sourceModule:"crm",dateWindow:"visit_date is inside the range.",scope:"PostgreSQL CRM scope.",emptyBehavior:"zero",format:"count",comparable:true }),
  metric({ key:"crm_interactions",displayName:"CRM interactions",definition:"Authorized CRM timeline interactions recorded in the selected range.",numerator:null,denominator:null,roles:CRM,sourceModule:"crm",dateWindow:"occurred_at is inside the range.",scope:"PostgreSQL CRM scope.",emptyBehavior:"zero",format:"count",comparable:true }),
  metric({ key:"notification_delivery_health",displayName:"Notification delivery health",definition:"Delivered notification jobs divided by terminal and delivered notification jobs in the selected range.",numerator:"delivered notification jobs",denominator:"delivered plus terminal failed jobs",roles:["super_admin","admin"],sourceModule:"notifications",dateWindow:"delivery creation time is inside the range.",scope:"Tenant-wide notification administration scope.",emptyBehavior:"no_data",format:"percentage",comparable:true }),
];

export function metricFor(key: string): MetricDefinition | undefined { return METRIC_CATALOG.find((item) => item.key === key); }

export function safeRate(numerator: number, denominator: number): number | null {
  return denominator <= 0 ? null : Math.round((numerator / denominator) * 10_000) / 100;
}

export function formatMetric(value: MetricValue, definition: MetricDefinition): string {
  if (value.value === null) return definition.emptyBehavior === "not_applicable" ? "Not applicable" : "No data";
  if (definition.format === "percentage") return `${value.value.toFixed(1)}%`;
  if (definition.format === "duration_minutes") {
    if (value.value < 60) return `${Math.round(value.value)} min`;
    if (value.value < 1_440) return `${(value.value / 60).toFixed(1)} hr`;
    return `${(value.value / 1_440).toFixed(1)} days`;
  }
  return Math.round(value.value).toLocaleString("en-IN");
}

export function emptyMetricValue(behavior: EmptyBehavior): number | null { return behavior === "zero" ? 0 : null; }
