"use client";

import { type FormEvent, useMemo, useState } from "react";
import { useRouter } from "@/next-shim/navigation"; // crm-port: next/navigation -> local shim (same paths, /crm base path added)
import { phoneDigits } from "@/lib/clients";
import { createClient } from "@/lib/supabase/client";
import { pushLeadToRuno } from "@/crm-port/phase4"; // crm-port: Runo push route -> Phase 4 stub

export type LeadField = { id: string; field_key: string; label: string; field_type: "text" | "number" | "dropdown" | "date" | "geo" | "file"; is_mandatory: boolean; is_hidden: boolean; display_order: number; is_runo_synced: boolean; runo_field_name: string | null; option_source: string | null };
export type LeadOption = { id: string; field_id: string; option_value: string; display_order: number; triggers_field_key: string | null };
function blank(value: string | undefined) { return !value?.trim(); }

export function LeadForm({ fields, options, lookupOptions, actorId }: { fields: LeadField[]; options: LeadOption[]; lookupOptions: Record<string, string[]>; actorId: string }) {
  const router = useRouter(); const [values, setValues] = useState<Record<string, string>>({ country: "India" }); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const optionsByField = useMemo(() => Object.groupBy(options, ({ field_id }) => field_id), [options]);
  const conditionalKeys = useMemo(() => new Set(["source_of_lead", "type_of_calling", "name_of_exhibition", "exhibition_name", "invitation_offer_name"]), []);
  const visibleKeys = useMemo(() => { const shown = new Set(fields.filter((field) => !field.is_hidden && !conditionalKeys.has(field.field_key)).map((field) => field.field_key)); let changed = true; while (changed) { changed = false; for (const field of fields) { const option = (optionsByField[field.id] ?? []).find((item) => item.option_value === values[field.field_key]); if (option?.triggers_field_key && !shown.has(option.triggers_field_key)) { shown.add(option.triggers_field_key); changed = true; } } } return shown; }, [conditionalKeys, fields, optionsByField, values]);
  const visibleFields = fields.filter((field) => visibleKeys.has(field.field_key) && !field.is_hidden).toSorted((a, b) => a.display_order - b.display_order);
  function setValue(key: string, value: string) { const next = { ...values, [key]: value }; const shown = new Set(fields.filter((field) => !field.is_hidden && !conditionalKeys.has(field.field_key)).map((field) => field.field_key)); let changed = true; while (changed) { changed = false; for (const field of fields) { const option = (optionsByField[field.id] ?? []).find((item) => item.option_value === next[field.field_key]); if (option?.triggers_field_key && !shown.has(option.triggers_field_key)) { shown.add(option.triggers_field_key); changed = true; } } } for (const existingKey of Object.keys(next)) if (!shown.has(existingKey)) delete next[existingKey]; setValues(next); }
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(""); const mobile = phoneDigits(values.mobile_no ?? ""); const missing = visibleFields.find((field) => field.is_mandatory && blank(values[field.field_key])); if (mobile.length !== 10 || missing) { setMessage(mobile.length !== 10 ? "Mobile number must contain exactly 10 digits." : `${missing!.label} is required.`); return; } const fieldValues = Object.fromEntries(Object.entries(values).filter(([key, value]) => key !== "mobile_no" && key !== "name" && visibleKeys.has(key) && !blank(value))); setSaving(true); const { data, error } = await createClient().from("leads").insert({ phone_number: mobile, name: values.name?.trim() || null, field_values: fieldValues, created_by: actorId }).select("id").single(); if (error || !data) { setSaving(false); setMessage(error?.code === "23505" ? "A lead with this mobile number already exists." : "Could not save the lead. Please try again."); return; } const response = await pushLeadToRuno(data.id) /* crm-port: /api/leads/[leadId]/runo is Phase 4; see pushLeadToRuno */; setSaving(false); setMessage(response.ok ? "Lead saved and pushed to Runo." : "Lead saved locally. Runo sync not yet configured."); router.refresh(); }
  return <section className="mt-6 max-w-4xl rounded-xl border bg-white p-5"><form className="grid gap-4 md:grid-cols-2" onSubmit={submit}>{visibleFields.map((field) => { const choices = field.option_source ? lookupOptions[field.option_source] ?? [] : (optionsByField[field.id] ?? []).toSorted((a, b) => a.display_order - b.display_order).map((option) => option.option_value); if (field.field_type === "file") return <p key={field.id} className="md:col-span-2 rounded bg-amber-50 p-3 text-sm text-amber-900">{field.label}: file fields require a lead-document storage policy and are not enabled yet.</p>; return <label className="text-sm" key={field.id}>{field.label}{field.is_mandatory ? " *" : ""}{field.field_type === "dropdown" ? <select aria-label={field.label} className="mt-1 block w-full rounded border p-2" value={values[field.field_key] ?? ""} onChange={(event) => setValue(field.field_key, event.target.value)}><option value="">Select {field.label}</option>{choices.map((choice) => <option key={choice} value={choice}>{choice}</option>)}</select> : <input aria-label={field.label} className="mt-1 block w-full rounded border p-2" type={field.field_type === "date" ? "date" : "text"} inputMode={field.field_key === "mobile_no" || field.field_type === "number" ? "numeric" : undefined} value={values[field.field_key] ?? ""} onChange={(event) => setValue(field.field_key, event.target.value)} />}</label>; })}<div className="md:col-span-2"><button disabled={saving} className="rounded bg-amber-800 px-4 py-2 font-medium text-white disabled:opacity-50">{saving ? "Saving..." : "Save lead"}</button>{message ? <p role="status" className="mt-3 text-sm text-stone-700">{message}</p> : null}</div></form></section>;
}
