"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "@/next-shim/navigation"; // crm-port: next/navigation -> local shim (same paths, /crm base path added)

import { phoneDigits } from "@/lib/clients";
import { createClient } from "@/lib/supabase/client";

type Props = { profile: { role: string; branch_id: string | null }; branches: { id: string; name: string }[]; initialPhone: string };

export function NewClientForm({ profile, branches, initialPhone }: Props) {
  const [name, setName] = useState(""); const [phone, setPhone] = useState(initialPhone); const [gender, setGender] = useState(""); const [branch, setBranch] = useState(profile.branch_id ?? ""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const router = useRouter();
  async function submit(event: FormEvent) { event.preventDefault(); if (!name.trim() || phoneDigits(phone).length !== 10) { setMessage("Name and a 10-digit phone are required."); return; } if (profile.role === "super_admin" && !branch) { setMessage("Choose a branch."); return; } setSaving(true); const { data, error } = await createClient().rpc("create_client_with_phone", { p_primary_name: name, p_primary_phone: phone, p_gender: gender || undefined, p_branch_id: profile.role === "super_admin" ? branch : undefined }); setSaving(false); if (!error && data) { router.push(`/clients/${data}`); return; } if (error?.code === "23505") { const { data: matches } = await createClient().rpc("search_clients", { search_text: phoneDigits(phone), result_limit: 1 }); if (matches?.[0]) { setMessage("This phone number already exists — opening that client."); router.push(`/clients/${matches[0].client_id}`); return; } } setMessage(error?.message.includes("phone") ? "This phone number already exists." : "Could not create the client. Please try again."); }
  return <form onSubmit={submit} className="mt-6 max-w-xl space-y-4 rounded-xl border bg-white p-6"><label className="block"><span className="text-sm font-medium">Primary name *</span><input className="mt-1 w-full rounded border p-2" value={name} onChange={(event) => setName(event.target.value)} /></label><label className="block"><span className="text-sm font-medium">Primary phone *</span><input className="mt-1 w-full rounded border p-2" value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="98765 43210" /></label><label className="block"><span className="text-sm font-medium">Gender</span><input className="mt-1 w-full rounded border p-2" value={gender} onChange={(event) => setGender(event.target.value)} /></label>{profile.role === "super_admin" ? <label className="block"><span className="text-sm font-medium">Branch *</span><select className="mt-1 w-full rounded border p-2" value={branch} onChange={(event) => setBranch(event.target.value)}><option value="">Choose branch</option>{branches.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label> : <p className="rounded bg-stone-100 p-3 text-sm">New clients are assigned to your own branch automatically.</p>}<button disabled={saving} className="rounded bg-amber-800 px-4 py-2 font-medium text-white disabled:opacity-50">{saving ? "Creating…" : "Create client"}</button>{message ? <p className="text-sm text-red-700">{message}</p> : null}</form>;
}
