import {supabase} from "@jewelos/api-client";
import {validateSectionControls,type BranchSettings,type SectionControls,type TenantSettings,type UserPreferences} from "@jewelos/core";
export type SettingsData={tenant:{id:string;name:string;currency:string|null;timezone:string|null;settings_version:number;export_retention_days:number;export_max_rows:number};branches:Array<{id:string;name:string;code:string;settings:Record<string,unknown>;settings_version:number}>;departments:Array<{id:string;name:string;branch_id:string|null}>;preferences:{preferences:UserPreferences;record_version:number}|null;sectionControls:SectionControls};
export async function fetchSettings():Promise<SettingsData>{const [tenant,branches,departments,preferences,sectionControls]=await Promise.all([supabase.from("tenants").select("id,name,currency,timezone,settings_version,export_retention_days,export_max_rows").single(),supabase.from("branches").select("id,name,code,settings,settings_version").eq("is_active",true).order("name"),supabase.from("departments").select("id,name,branch_id").eq("is_active",true).order("name"),supabase.from("user_preferences").select("preferences,record_version").maybeSingle(),supabase.rpc("get_section_availability")]);const error=tenant.error??branches.error??departments.error??preferences.error??sectionControls.error;if(error)throw error;return {tenant:tenant.data as SettingsData["tenant"],branches:(branches.data??[]) as SettingsData["branches"],departments:(departments.data??[]) as SettingsData["departments"],preferences:preferences.data as SettingsData["preferences"],sectionControls:validateSectionControls(sectionControls.data)};}
export async function savePreferences(preferences:UserPreferences){const {error}=await supabase.rpc("save_user_preferences_with_audit",{p_preferences:preferences});if(error)throw error;}
export async function saveTenant(settings:TenantSettings,version:number){const {error}=await supabase.rpc("save_tenant_settings_with_audit",{p_settings:settings,p_expected_version:version,p_request_key:crypto.randomUUID()});if(error)throw error;}
export async function saveBranch(id:string,settings:BranchSettings,version:number){const {error}=await supabase.rpc("save_branch_settings_with_audit",{p_branch_id:id,p_settings:settings,p_expected_version:version,p_request_key:crypto.randomUUID()});if(error)throw error;}
export async function saveSectionControls(controls:SectionControls):Promise<SectionControls>{const {data,error}=await supabase.rpc("save_section_availability_with_audit",{p_developer_mode_enabled:controls.developer_mode_enabled,p_section_availability:controls.section_availability,p_expected_version:controls.settings_version,p_request_key:crypto.randomUUID()});if(error)throw error;return validateSectionControls(data);}
export type ProductionDemoDataRetirementPreview={operation_id:string;manifest_hash:string;expires_at:string;removal_counts:Record<string,number>;retained_counts:Record<string,number>};
function retirementData(data:unknown):Record<string,unknown>{if(typeof data!=="object"||data===null||!("data" in data)||typeof (data as {data:unknown}).data!=="object"||(data as {data:unknown}).data===null)throw new Error("Retirement operation returned an invalid response.");return (data as {data:Record<string,unknown>}).data;}
export async function previewProductionDemoDataRetirement(backupReference:string):Promise<ProductionDemoDataRetirementPreview>{const {data,error}=await supabase.functions.invoke("production-demo-data-retirement",{method:"POST",body:{action:"preview",backup_reference:backupReference,maintenance_acknowledged:true}});if(error)throw new Error("Unable to create retirement preview.");const value=retirementData(data);if(typeof value.operation_id!=="string"||typeof value.manifest_hash!=="string"||typeof value.expires_at!=="string")throw new Error("Retirement preview returned an invalid response.");return {operation_id:value.operation_id,manifest_hash:value.manifest_hash,expires_at:value.expires_at,removal_counts:(typeof value.removal_counts==="object"&&value.removal_counts!==null?value.removal_counts:{}) as Record<string,number>,retained_counts:(typeof value.retained_counts==="object"&&value.retained_counts!==null?value.retained_counts:{}) as Record<string,number>};}
export async function executeProductionDemoDataRetirement(input:{operationId:string;manifestHash:string;confirmation:"RETIRE DEMO DATA"}):Promise<void>{const {data,error}=await supabase.functions.invoke("production-demo-data-retirement",{method:"POST",body:{action:"execute",operation_id:input.operationId,manifest_hash:input.manifestHash,confirmation:input.confirmation}});if(error)throw new Error("Retirement execution was denied, expired, or changed.");retirementData(data);}
