// @vitest-environment jsdom
import {afterEach,describe,expect,it,vi} from "vitest";
import {cleanup,render,screen,fireEvent,waitFor} from "@testing-library/react";
const read=vi.hoisted(()=>({summary:vi.fn(),options:vi.fn(),records:vi.fn()}));
vi.mock("@/lib/crm-insights-api",()=>({readCrmInsightsFilter:()=>({version:1,preset:"this_month",tab:"visits",groupBy:"branch"}),fetchCrmInsights:read.summary,fetchCrmInsightsOptions:read.options,fetchCrmInsightRecords:read.records}));
import {CrmInsightsDashboard} from "@/components/dashboard-insights/CrmInsightsDashboard";
afterEach(()=>{cleanup();vi.clearAllMocks();window.history.replaceState({},"","/");});
describe("CRM insights",()=>{it("keeps CRM metrics and opens matching follow-up records",async()=>{read.summary.mockResolvedValue({version:1,generatedAt:"2026-10-09T08:00:00Z",timezone:"Asia/Kolkata",from:"2026-10-01",to:"2026-10-09",scopeLabel:"CRM",moduleStates:{crm:true},metrics:[{key:"overdue_followups",label:"Overdue follow-ups",value:3,previous:null,numerator:null,denominator:null,basis:"current",module:"crm"}],trend:[],groups:[],outcomes:[],groupBasis:"Current follow-ups"});read.options.mockResolvedValue({branches:[],salespeople:[],crm:[],sources:[],outcomes:[],visitTypes:[]});read.records.mockResolvedValue({rows:[],total:3,offset:0,limit:25});render(<CrmInsightsDashboard/>);fireEvent.click(await screen.findByRole("button",{name:/Contact overdue follow-ups/}));await waitFor(()=>expect(read.records).toHaveBeenCalledWith(expect.anything(),"overdue_followups",undefined,0));expect(screen.queryByText("Tasks due")).toBeNull();});});

it("never reads company-wide metrics when a requested native branch has no mapping",async()=>{window.history.replaceState({},"","/?jewelos_branch_id=missing");read.options.mockResolvedValue({branches:[],salespeople:[],crm:[],sources:[],outcomes:[],visitTypes:[]});render(<CrmInsightsDashboard/>);expect((await screen.findByRole("alert")).textContent).toContain("no CRM mapping");expect(read.summary).not.toHaveBeenCalled();});
it("resolves the native branch before metrics",async()=>{window.history.replaceState({},"","/?jewelos_branch_id=internal-branch");read.options.mockResolvedValue({branches:[{id:"crm-branch",name:"Synthetic branch",jewelos_branch_id:"internal-branch"}],salespeople:[],crm:[],sources:[],outcomes:[],visitTypes:[]});render(<CrmInsightsDashboard/>);await waitFor(()=>expect(read.summary).toHaveBeenCalledWith(expect.objectContaining({branch_id:"crm-branch"})));expect(read.summary.mock.calls.every(call=>call[0].branch_id==="crm-branch")).toBe(true);});

it("restores a management metric URL as the exact CRM record drawer",async()=>{window.history.replaceState({},"","/?metric=overdue_followups");read.options.mockResolvedValue({branches:[],salespeople:[],crm:[],sources:[],outcomes:[],visitTypes:[]});render(<CrmInsightsDashboard/>);await waitFor(()=>expect(read.records).toHaveBeenCalledWith(expect.anything(),"overdue_followups",undefined,0));});
