import { loadCrmMasterOptions } from "@/crm-port/master-options";

import { readCrmResults } from "@/crm-port/read-results";
import { getCrmUser } from "@/crm-port/crm-user"; // crm-port: see getCrmUser
import { WalkInForm } from "@/components/walk-in-form";
import { redirect } from "@/next-shim/navigation"; // crm-port: next/navigation -> local shim (same paths, /crm base path added)
import { createClient } from "@/lib/supabase/server";
import { availableCrmNames } from "@/lib/available-crm-names";
import { kolkataDateKey } from "@/lib/business-date";

export default async function NewVisitPage({ searchParams }: { searchParams: Promise<{ queue?: string }> }) {
  const params = await searchParams; const supabase = await createClient(); const masterOptionsPromise=loadCrmMasterOptions(supabase); const [{ data: profileRows }, { data: auth }] = await readCrmResults([supabase.rpc("get_my_profile"), getCrmUser(supabase) /* crm-port: auth.getUser().id is used as the CRM user id -> crm.current_crm_user_id() */]); const profile = profileRows?.[0]; if (!profile || !auth.user) return null;

  if (!params.queue) redirect("/queue");
  const [{ data: user }, { data: branches }, queueResult] = await readCrmResults([supabase.from("users").select("branch_id,name").eq("id", auth.user.id).single(), supabase.from("branches").select("id,name").eq("active", true).order("name"), params.queue ? supabase.from("entry_queue").select("id,client_name,mobile,branch_id,assigned_crm_name,client_id,client_is_new,status").eq("id", params.queue).single() : Promise.resolve({ data: null })]);
  if (!queueResult.data || queueResult.data.status === "complete") redirect("/queue");
  const selectedClientId = queueResult.data.client_id;
  const branchId = queueResult.data?.branch_id ?? user?.branch_id ?? "";
  const today = kolkataDateKey();
  const [{ data: allocation }, { data: availability }, { data: productCategories }, { data: notBoughtReasons }, { data: beverages }, { data: snacks }, { data: relations }, { data: sugarOptions }, { data: sourceOfLeads }, { data: communities }, { data: gifts }, { data: client }, { data: salespeople }] = await readCrmResults([supabase.from("crm_allocation").select("branch_id,crm_name").eq("active", true).order("crm_name").order("id") /* crm-port: deterministic order */, supabase.from("crm_daily_availability").select("branch_id,crm_name,is_available").eq("date", today), masterOptionsPromise.then(options=>({data:(options.lookup_product_categories ?? []).map(label=>({label}))})), masterOptionsPromise.then(options=>({data:(options.lookup_not_bought_reasons ?? []).map(label=>({label}))})), masterOptionsPromise.then(options=>({data:(options.lookup_beverages ?? []).map(label=>({label}))})), masterOptionsPromise.then(options=>({data:(options.lookup_snacks ?? []).map(label=>({label}))})), masterOptionsPromise.then(options=>({data:(options.lookup_relations ?? []).map(label=>({label}))})), masterOptionsPromise.then(options=>({data:(options.lookup_sugar_options ?? []).map(label=>({label}))})), masterOptionsPromise.then(options=>({data:(options.lookup_source_of_leads ?? []).map(label=>({label}))})), masterOptionsPromise.then(options=>({data:(options.lookup_communities ?? []).map(label=>({label}))})), masterOptionsPromise.then(options=>({data:(options.lookup_gifts ?? []).map(label=>({label}))})), selectedClientId ? supabase.from("clients").select("*").eq("client_id", selectedClientId).single() : Promise.resolve({ data: null }), supabase.rpc("get_walkin_salespeople")]);
  const salespeopleByBranch = Object.fromEntries((branches ?? []).map(branch => [branch.id, (salespeople ?? []).filter(person => person.branch_id === branch.id).map(person => ({ id: person.salesperson_id, name: person.salesperson_name }))]));
  const crmByBranch = Object.fromEntries((branches ?? []).map((branch) => [branch.id, availableCrmNames((allocation ?? []).filter((item) => item.branch_id === branch.id), (availability ?? []).filter((item) => item.branch_id === branch.id))]));
  return <main className="mx-auto max-w-7xl px-5 py-7"><p className="text-sm font-semibold uppercase tracking-wider text-amber-800">Visit intake</p><h1 className="mt-1 text-3xl font-semibold">Walk-in visit form</h1><p className="mt-2 text-stone-600">The client record and ID are already registered. Submit this form to save the visit details.</p><WalkInForm profile={{ role: profile.role, branchId: user?.branch_id ?? null, name: user?.name ?? "" }} branches={branches ?? []} crms={crmByBranch[branchId] ?? []} crmByBranch={crmByBranch} salespeopleByBranch={salespeopleByBranch} queue={queueResult.data} client={client} lookups={{ masterFields: await masterOptionsPromise, productCategories: (productCategories ?? []).map((item) => item.label), notBoughtReasons: (notBoughtReasons ?? []).map((item) => item.label), beverages: (beverages ?? []).map((item) => item.label), snacks: (snacks ?? []).map((item) => item.label), relations: (relations ?? []).map((item: { label: string }) => item.label), sugarOptions: (sugarOptions ?? []).map((item: { label: string }) => item.label), sourceOfLeads: (sourceOfLeads ?? []).map((item: { label: string }) => item.label), communities: (communities ?? []).map((item) => item.label), gifts: (gifts ?? []).map((item) => item.label) }} /></main>;

}
