import { FollowupQueue } from "@/components/followup-queue";
import { legacyNotBoughtHistory } from "@/lib/followup-logic";
import { createClient } from "@/lib/supabase/server";
export default async function FollowupsPage() {
 const supabase=await createClient(); const [{data:profileRows},{data:auth}] = await Promise.all([supabase.rpc("get_my_profile"),supabase.auth.getUser()]); const profile=profileRows?.[0]; if(!profile||!auth.user)return null;
 const db=supabase as any; const {data:followups}=await db.from("not_bought_followups").select("id,client_id,reference_number,status,next_followup_date,remark,action_point,branch_id,followup_count,source_timeline_id,source_visit_form_id,clients!inner(primary_name,primary_phone),client_timeline(event_date,crm_name,seen_categories,product_requirement,remark),visit_forms(not_bought_reasons,not_bought_other)");
 const rows=followups??[]; const {data:history}=await db.from("not_bought_history").select("followup_id,status,previous_status,call_response,remark,created_at,updated_by,not_bought_followups!inner(client_id,reference_number)").order("created_at",{ascending:false}); const normalizedHistory=(history??[]).map((entry:any)=>({...entry,client_id:entry.not_bought_followups.client_id,reference_number:entry.not_bought_followups.reference_number}));
 const items=rows.map((row:any)=>{const timeline=row.client_timeline??{};const form=row.visit_forms??{};const h=legacyNotBoughtHistory(normalizedHistory,row.client_id,row.reference_number);return {id:row.id,client_id:row.client_id,reference_number:row.reference_number,status:row.status,next_followup_date:row.next_followup_date,remark:row.remark,action_point:row.action_point,branch_id:row.branch_id,client_name:row.clients.primary_name,phone:row.clients.primary_phone,crm_name:timeline.crm_name??"",visit_date:timeline.event_date??null,reason:[...(form.not_bought_reasons??[]),form.not_bought_other].filter(Boolean).join(", "),seen_categories:(timeline.seen_categories??[]).join(", "),product_requirement:timeline.product_requirement??"",product_seen_remark:timeline.remark??"",followup_count:row.followup_count,history_count:h.length,remark_history:h.map((entry:any)=>`${entry.created_at}: ${entry.status}${entry.remark?` — ${entry.remark}`:""}`).join("\n")};});
 const crmNames=[...new Set(items.map((item:any)=>item.crm_name).filter(Boolean))].sort() as string[]; return <FollowupQueue role={profile.role} branchId={null} items={items} crmNames={crmNames} enteredByName={profile.name??auth.user.email??"Current user"}/>;
}
