import { useCallback, useEffect, useState } from "react";
import { CalendarClock, RefreshCw } from "lucide-react";
import { useAuth } from "@/auth/AuthContext";
import { Button, Modal, Notice } from "@/components/ui";
import { cancelFollowup, completeFollowup, loadFollowups, rescheduleFollowup } from "./api";
import type { CrmFollowup, CrmOptions } from "./types";

const TABS=["today","overdue","upcoming","completed"] as const;
export function FollowupsPanel({options,onOpenClient}:{options:CrmOptions;onOpenClient:(id:string)=>void}){const{profile}=useAuth();const[tab,setTab]=useState<typeof TABS[number]>("today");const[items,setItems]=useState<CrmFollowup[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[action,setAction]=useState<{item:CrmFollowup;kind:"reschedule"|"complete"|"cancel"}|null>(null);const[assignedToMe,setAssignedToMe]=useState(true);
  const refresh=useCallback(async()=>{if(!profile)return;setLoading(true);setError(null);try{setItems(await loadFollowups({bucket:tab,assigned_to:assignedToMe?profile.id:undefined,branch_id:profile.user_role==="manager"?profile.branch_id:undefined,limit:100}));}catch(caught){setError(caught instanceof Error?caught.message:"Follow-ups failed");}finally{setLoading(false);}},[assignedToMe,profile,tab]);useEffect(()=>{void refresh();},[refresh]);
 return <section className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-xl font-semibold text-task-text"><CalendarClock className="size-5 text-task-accent"/>Follow-ups</h2><p className="text-sm text-task-text-muted">Tenant-timezone queues and PostgreSQL-authoritative transitions.</p></div><Button onClick={()=>void refresh()} variant="secondary"><RefreshCw className="size-4"/>Refresh</Button></div><div className="flex flex-wrap gap-2">{TABS.map((item)=><Button key={item} onClick={()=>setTab(item)} variant={tab===item?"primary":"secondary"}>{item[0]!.toUpperCase()+item.slice(1)}</Button>)}<label className="ml-auto flex items-center gap-2 text-sm text-task-text"><input checked={assignedToMe} onChange={(event)=>setAssignedToMe(event.target.checked)} type="checkbox"/>Assigned to me</label></div>{error?<Notice tone="danger">{error}</Notice>:null}{loading?<div className="h-32 animate-pulse rounded-xl bg-task-muted"/>:items.length===0?<Notice tone="task">No follow-ups in this queue.</Notice>:<div className="grid gap-3">{items.map((item)=><article className="rounded-xl border border-task-border bg-task-bg p-4" key={item.id}><div className="flex flex-wrap items-start justify-between gap-3"><button className="text-left" onClick={()=>onOpenClient(item.client_id)} type="button"><p className="font-semibold text-task-text">{item.client_display||"Authorized client"}</p><p className="text-sm text-task-text-muted">{item.subject||"Follow-up"} · due {item.due_date}</p></button>{item.status==="open"?<div className="flex flex-wrap gap-2"><Button onClick={()=>setAction({item,kind:"reschedule"})} variant="secondary">Reschedule</Button><Button onClick={()=>setAction({item,kind:"complete"})}>Complete</Button><Button onClick={()=>setAction({item,kind:"cancel"})} variant="danger">Cancel</Button></div>:<span className="rounded-full bg-task-muted px-3 py-1 text-xs text-task-text-muted">{item.status}</span>}</div></article>)}</div>}{action?<FollowupAction action={action} options={options} onClose={()=>setAction(null)} onDone={async()=>{setAction(null);await refresh();}}/>:null}</section>;
}
function FollowupAction({action,options,onClose,onDone}:{action:{item:CrmFollowup;kind:"reschedule"|"complete"|"cancel"};options:CrmOptions;onClose:()=>void;onDone:()=>Promise<void>}){const[due,setDue]=useState(action.item.due_date);const[assigned,setAssigned]=useState(action.item.assigned_to??"");const[text,setText]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const submit=async()=>{setBusy(true);setError(null);try{if(action.kind==="reschedule")await rescheduleFollowup(action.item.id,due,assigned,text,action.item.record_version);else if(action.kind==="complete")await completeFollowup(action.item.id,text,action.item.record_version);else await cancelFollowup(action.item.id,text,action.item.record_version);await onDone();}catch(caught){setError(caught instanceof Error?caught.message:"Follow-up action failed");setBusy(false);}};return <Modal onClose={onClose} title={`${action.kind[0]!.toUpperCase()+action.kind.slice(1)} follow-up`}><div className="space-y-4">{error?<Notice tone="danger">{error}</Notice>:null}{action.kind==="reschedule"?<><label><span className="label">New due date</span><input className="field" onChange={(e)=>setDue(e.target.value)} type="date" value={due}/></label><label><span className="label">Assignee</span><select className="field" onChange={(e)=>setAssigned(e.target.value)} value={assigned}>{options.profiles.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label></>:null}<label><span className="label">{action.kind==="complete"?"Outcome":"Reason"} *</span><textarea className="field min-h-24" onChange={(e)=>setText(e.target.value)} value={text}/></label><Button className="w-full" disabled={busy||!text.trim()||(action.kind==="reschedule"&&!assigned)} onClick={()=>void submit()}>{busy?"Saving…":"Confirm"}</Button></div></Modal>;}
