// A throwaway local Supabase stack that runs the ORIGINAL CRM schema (its Prisma migrations,
// unmodified, in schema public) for the parity harness. It uses its own project id and ports
// (5632x), so it never touches the JewelOS stack or any other local stack. Local only.
import { copyFileSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { REPO_ROOT, run } from "./util.mjs";

export const ORIGINAL_PROJECT_ID = "jewelos-crm-parity-original";
export const ORIGINAL_API_URL = "http://127.0.0.1:56321";
export const ORIGINAL_DB_CONTAINER = `supabase_db_${ORIGINAL_PROJECT_ID}`;

const ORIGINAL_MIGRATIONS = join(REPO_ROOT, "sreejith-crm", "web-app", "prisma", "migrations");
// The same replay range as the Phase 2 port (20260723000000 .. 20260803010000). The SSO
// migration is excluded there too (its artefacts are replaced by the identity bridge), and it
// does not apply on PostgreSQL 17 ("grant" is used as a table alias). Without it the original
// resolves the CRM user as users.id = auth.uid(), which the fixture uses.
const EXCLUDED_MIGRATIONS = new Set(["20260820110000_crm_sso_access_foundation"]);

const CONFIG = `# Generated by scripts/crm-parity/original-stack.mjs (local parity harness only).
project_id = "${ORIGINAL_PROJECT_ID}"

[api]
enabled = true
port = 56321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 56322
shadow_port = 56320
major_version = 17

[db.pooler]
enabled = false
port = 56329

[db.seed]
enabled = false

[realtime]
enabled = false

[studio]
enabled = false
port = 56323

[local_smtp]
enabled = false
port = 56324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3300"

[edge_runtime]
enabled = false

[analytics]
enabled = false
port = 56327
`;

/** Writes the stack workdir: config plus the original migrations in timestamp order. */
export function prepareOriginalStack(workdir) {
  const supabaseDir = join(workdir, "supabase");
  rmSync(join(supabaseDir, "migrations"), { recursive: true, force: true });
  mkdirSync(join(supabaseDir, "migrations"), { recursive: true });
  writeFileSync(join(supabaseDir, "config.toml"), CONFIG);
  const folders = readdirSync(ORIGINAL_MIGRATIONS, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && /^\d{14}_/.test(entry.name) && !EXCLUDED_MIGRATIONS.has(entry.name))
    .map((entry) => entry.name)
    .sort();
  for (const folder of folders) {
    // Only the schema SQL is copied; the reference project's data, env files and reports are not.
    copyFileSync(join(ORIGINAL_MIGRATIONS, folder, "migration.sql"), join(supabaseDir, "migrations", `${folder}.sql`));
  }
  return folders.length;
}

export function startOriginalStack(workdir) {
  run("supabase.cmd", ["start", "--workdir", workdir], { timeoutMs: 900_000 });
  // A clean database for every run: all original migrations, then the synthetic fixture.
  run("supabase.cmd", ["db", "reset", "--workdir", workdir], { timeoutMs: 900_000 });
}

export function stopOriginalStack(workdir) {
  run("supabase.cmd", ["stop", "--workdir", workdir, "--no-backup"], { timeoutMs: 300_000, allowFailure: true });
}
