import {AlarmClock,ArrowRight,Bell,CheckCircle2,ClipboardCheck,ClipboardList,FileText,Gem,GitBranch,Users} from "lucide-react";
import {useAuth} from "@/auth/AuthContext";
import {titleCase} from "@/lib/format";
import {fetchHomeSummary} from "@/features/analytics/api";
import {EmptyMessage,ErrorPanel,LoadingPanels,Panel,StatusDot} from "@/features/analytics/components";
import {useAsyncData} from "@/features/analytics/useAsyncData";
import type {HomeSummary} from "@/features/analytics/types";

const routeLabel:Record<string,string>={"/tasks":"Tasks","/tasks/fms":"FMS Tasks","/forms":"Forms","/crm":"CRM","/reports":"Reports"};
const routeIcon:Record<string,typeof ClipboardList>={"/tasks":ClipboardList,"/tasks/fms":GitBranch,"/forms":FileText,"/crm":Users,"/reports":ClipboardCheck};

function greeting(timezone:string){const hour=Number(new Intl.DateTimeFormat("en-IN",{hour:"2-digit",hour12:false,timeZone:timezone}).format(new Date()));return hour<12?"Good Morning":hour<17?"Good Afternoon":"Good Evening";}
function completion(summary:HomeSummary){const tasks=summary.tasks;return tasks.length?Math.round(tasks.filter((task)=>task.status==="completed").length/tasks.length*100):0;}
function WorkPanel({title,caption,count,Icon,children,onOpen}:{title:string;caption:string;count:number;Icon:typeof ClipboardList;children:React.ReactNode;onOpen:()=>void}){return <button className="group w-72 shrink-0 snap-center rounded-2xl border border-task-border bg-task-bg p-4 text-left shadow-sm transition hover:border-gold/50 hover:bg-task-muted focus-visible:ring-gold" onClick={onOpen} type="button"><div className="mb-3 flex items-center justify-between"><span className="flex size-10 items-center justify-center rounded-xl bg-gold text-obsidian"><Icon className="size-5"/></span><span className="text-2xl font-semibold tabular-nums">{count}</span></div><p className="text-sm font-semibold">{title}</p><p className="mt-0.5 text-xs text-task-text-muted">{caption}</p><div className="mt-3 min-h-12 border-t border-task-border pt-3 text-xs text-task-text-muted group-hover:text-task-text">{children}</div></button>}

export function HomeView({onNavigate}:{onNavigate:(path:string)=>void}){
  const {branch,profile}=useAuth();
  const {data,error,loading,retry}=useAsyncData(fetchHomeSummary,[]);
  if(loading)return <section className="-m-4 min-h-[calc(100dvh-7.875rem)] bg-task-muted p-4 sm:-m-6 sm:p-6"><LoadingPanels count={6}/></section>;
  if(error)return <section className="-m-4 min-h-[calc(100dvh-7.875rem)] bg-task-muted p-4 sm:-m-6 sm:p-6"><ErrorPanel message={error} onRetry={retry}/></section>;
  if(!data)return null;
  const completed=data.tasks.filter((task)=>task.status==="completed").length;
  const priority=data.tasks.filter((task)=>task.status!=="completed"&&task.priority==="high").slice(0,3);
  const task=data.tasks.find((item)=>item.status!=="completed")??{id:"no-assigned-task",title:"No assigned tasks",due_at:new Date().toISOString(),overdue:false};
  const pct=completion(data);
  const quickActions=data.quick_actions.filter((path)=>routeLabel[path]);
  return <section className="-m-4 min-h-[calc(100dvh-7.875rem)] overflow-hidden bg-task-muted text-task-text sm:-m-6 md:min-h-[calc(100vh-4rem)]">
    <header className="bg-charcoal px-4 pb-8 pt-6 sm:px-6">
      <div className="mx-auto max-w-7xl">
        <div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="text-sm text-champagne/70">{greeting(data.timezone)},</p><h1 className="mt-0.5 truncate font-display text-3xl text-white">{profile?.employee_name.split(" ")[0]??"User"}</h1><div className="mt-2 flex flex-wrap gap-2 text-xs"><span className="rounded-full border border-gold/30 bg-gold/10 px-2.5 py-1 font-medium text-gold">{titleCase(profile?.user_role??data.profile.role)}</span><span className="self-center text-champagne/65">{data.profile.branch_name??branch?.name??"Branch unavailable"}</span></div></div><div className="relative shrink-0"><div className="flex size-14 items-center justify-center rounded-2xl bg-gold text-obsidian shadow-lg shadow-gold/15"><Gem className="size-7"/></div>{data.unread_notifications>0?<span className="absolute -right-1 -top-1 flex size-5 items-center justify-center rounded-full bg-task-overdue text-[10px] font-bold text-white">{data.unread_notifications}</span>:null}</div></div>
        <div className="mt-6 rounded-2xl border border-gold/20 bg-obsidian/45 p-4"><div className="mb-2 flex items-center justify-between"><span className="text-sm font-medium text-white">Today's Completion</span><span className="text-lg font-semibold text-gold">{pct}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-gold transition-[width] duration-700" style={{width:`${pct}%`}}/></div><div className="mt-4 grid grid-cols-4 gap-2"><HeroStat label="Tasks" value={data.tasks.length}/><HeroStat label="Done" value={completed}/><HeroStat label="FMS" value={data.fms_stages.length}/><HeroStat label="Alerts" value={data.unread_notifications}/></div></div>
      </div>
    </header>
    <div className="-mt-4 rounded-t-3xl bg-task-muted px-4 pb-24 pt-6 sm:px-6"><div className="mx-auto max-w-7xl">
      <section><div className="mb-3 flex items-end justify-between gap-3"><div><h2 className="text-lg font-semibold">Action required</h2><p className="mt-1 text-sm text-task-text-muted">Your assigned tasks, FMS steps, and deadlines are shown first.</p></div><AlarmClock className="size-5 text-task-accent"/></div><div className="grid gap-3 lg:grid-cols-3"><ActionItem description={`Due ${new Date(task.due_at).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})}`} key={task.id} label={task.overdue?"Overdue — open now":"Assigned task"} onOpen={()=>onNavigate("/tasks")} overdue={task.overdue} title={task.title}/>{data.tasks.filter((task)=>task.status!=="completed").slice(0,4).map((task)=><ActionItem description={`Due ${new Date(task.due_at).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})}`} key={task.id} label={task.overdue?"Overdue — open now":"Assigned task"} onOpen={()=>onNavigate("/tasks")} overdue={task.overdue} title={task.title}/>)}</div></section>
      <section><h2 className="mb-3 text-xs font-semibold uppercase tracking-[0.16em] text-task-text-muted">Your day at a glance</h2><div className="-mx-4 flex snap-x gap-3 overflow-x-auto px-4 pb-2 sm:-mx-6 sm:px-6"><WorkPanel Icon={ClipboardList} caption="Assigned to you" count={data.tasks.filter((task)=>task.status!=="completed").length} onOpen={()=>onNavigate("/tasks")} title="My Daily Tasks">{data.tasks.length?data.tasks.slice(0,2).map((task)=><p className="truncate" key={task.id}>• {task.title}</p>):"Nothing waiting"}</WorkPanel><WorkPanel Icon={GitBranch} caption="Waiting for action" count={data.fms_stages.length} onOpen={()=>onNavigate("/tasks/fms")} title="FMS Tasks">{data.fms_stages.length?data.fms_stages.slice(0,2).map((stage)=><p className="truncate" key={stage.stage_id}>• {stage.stage_name}</p>):"Nothing waiting"}</WorkPanel><WorkPanel Icon={FileText} caption="Task-linked submissions" count={data.forms_awaiting_submission.length} onOpen={()=>onNavigate("/forms")} title="Forms">{data.forms_awaiting_submission.length?data.forms_awaiting_submission.slice(0,2).map((form)=><p className="truncate" key={form.task_id}>• {form.form_name}</p>):"Nothing waiting"}</WorkPanel><WorkPanel Icon={Bell} caption="Unread notifications" count={data.unread_notifications} onOpen={()=>onNavigate("/notifications")} title="Alerts">{data.unread_notifications?"Review your notification center":"No unread alerts"}</WorkPanel></div></section>
      {quickActions.length?<section className="mt-7"><h2 className="mb-3 text-lg font-semibold">Quick Actions</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{quickActions.map((path)=>{const Icon=routeIcon[path]??CheckCircle2;return <button className="flex min-h-24 flex-col items-center justify-center gap-2 rounded-2xl border border-task-border bg-task-bg p-3 text-center transition hover:border-gold/50 hover:bg-task-muted" key={path} onClick={()=>onNavigate(path)} type="button"><span className="flex size-10 items-center justify-center rounded-xl bg-gold/15 text-gold"><Icon className="size-5"/></span><span className="text-xs font-medium">{routeLabel[path]}</span></button>;})}</div></section>:null}
      <section className="mt-7"><div className="mb-3 flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">Priority Tasks Today</h2><button className="inline-flex min-h-10 items-center gap-1 text-sm font-semibold text-task-accent" onClick={()=>onNavigate("/tasks")} type="button">View all<ArrowRight className="size-4"/></button></div>{priority.length?<div className="grid gap-3 lg:grid-cols-3">{priority.map((task)=><article className="rounded-xl border border-task-border bg-task-bg p-4" key={task.id}><div className="flex gap-3"><StatusDot tone={task.overdue?"danger":"warning"}/><div className="min-w-0 flex-1"><p className="truncate font-semibold">{task.title}</p><p className="mt-1 text-xs text-task-text-muted">Due {new Date(task.due_at).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})}</p><p className="mt-2 text-xs font-medium text-task-overdue">{task.overdue?"Overdue":"High priority"}</p></div></div></article>)}</div>:<EmptyMessage>No high-priority work is waiting.</EmptyMessage>}</section>
      <section className="mt-7 grid gap-4 xl:grid-cols-[minmax(0,1.15fr)_minmax(20rem,.85fr)]"><Panel description="Visible only within your authorized CRM scope." title="CRM Follow-ups Due">{data.crm_followups.length?<ul className="space-y-3">{data.crm_followups.map((followup)=><li className="flex items-start gap-3" key={followup.id}><StatusDot tone={followup.overdue?"danger":"warning"}/><div><p className="text-sm font-medium">{followup.subject??"Follow-up"}</p><p className="text-xs text-task-text-muted">Due {followup.due_date}{followup.overdue?" · Overdue":""}</p></div></li>)}</ul>:<EmptyMessage>No CRM follow-ups are due.</EmptyMessage>}</Panel><Panel description="Bounded and authorized audit activity." title="Recent Activity">{data.recent_activity.length?<ul className="space-y-3">{data.recent_activity.map((activity)=><li className="flex items-start justify-between gap-3 text-sm" key={activity.id}><span><span className="font-medium">{titleCase(activity.action)}</span><span className="block text-xs text-task-text-muted">{titleCase(activity.module)}</span></span><time className="shrink-0 text-xs text-task-text-muted">{new Date(activity.created_at).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})}</time></li>)}</ul>:<EmptyMessage>No recent activity.</EmptyMessage>}</Panel></section>
    </div></div>
  </section>;
}
function HeroStat({label,value}:{label:string;value:number}){return <div className="text-center"><p className="text-xl font-semibold tabular-nums text-white">{value}</p><p className="text-xs text-champagne/60">{label}</p></div>}
function ActionItem({title,description,label,overdue,onOpen}:{title:string;description:string;label:string;overdue:boolean;onOpen:()=>void}){return <button className="rounded-2xl border border-task-border bg-task-bg p-4 text-left transition hover:border-gold/50 hover:bg-task-muted" onClick={onOpen} type="button"><div className="flex gap-3"><StatusDot tone={overdue?"danger":"warning"}/><div className="min-w-0"><p className="truncate font-semibold">{title}</p><p className="mt-1 text-xs text-task-text-muted">{description}</p><p className={`mt-2 text-xs font-semibold ${overdue?"text-task-overdue":"text-task-accent"}`}>{label}</p></div></div></button>}
