import { normalizeFmsDefinition, type FmsFlowDefinition, type FmsStageDefinition } from "@jewelos/core";
import type { FmsData, FmsFlowRow } from "./api";

export const newFmsStage = (type: FmsStageDefinition["type"], order: number): FmsStageDefinition => ({ key: `stage_${order + 1}`, name: type.split("_").map((part) => part[0]!.toUpperCase() + part.slice(1)).join(" "), type, order, required: true, completionRule: type === "approval" ? "manager_approval" : "any_doer", allowMultipleDoers: false, requiresUpload: false, requiresRemark: false, checklist: [], assigneeRules: [], requiresNextDoerHandoff: false, canMoveBackward: false, canReject: type === "approval", canRequestRevision: type === "approval", canEscalate: false, branchRules: type === "branch" ? [{ id: crypto.randomUUID(), source: "outcome", operator: "default", order: 0 }] : [], parallelTargetStageKeys: [], joinRequiredStageKeys: [], sla: { dueDate: "" } });

export function removeFmsStage(stages: readonly FmsStageDefinition[], key: string): readonly FmsStageDefinition[] {
  const removed = stages.find((stage) => stage.key === key);
  const replacement = removed?.type === "branch" || removed?.type === "parallel_start" ? undefined : removed?.defaultNextStageKey;
  return stages.filter((stage) => stage.key !== key).map((stage) => ({
    ...stage,
    defaultNextStageKey: stage.defaultNextStageKey === key ? replacement : stage.defaultNextStageKey,
    branchRules: stage.branchRules.map((rule) => rule.nextStageKey === key ? { ...rule, nextStageKey: replacement } : rule),
    parallelTargetStageKeys: stage.parallelTargetStageKeys.filter((target) => target !== key),
    joinRequiredStageKeys: stage.joinRequiredStageKeys.filter((target) => target !== key),
  }));
}

export function flowToDefinition(flow: FmsFlowRow | null, data: FmsData): FmsFlowDefinition {
  if (!flow) return { name: "", description: "", scope: "tenant", manualTrigger: true, stages: [] };
  const rows = data.stages.filter((stage) => stage.fms_flow_id === flow.id); const keyById = new Map(rows.map((stage) => [stage.id, stage.stage_key]));
  return normalizeFmsDefinition({ id: flow.id, familyId: flow.family_id, version: flow.version, lifecycle: flow.status, name: flow.name, description: flow.description ?? "", scope: flow.scope_type, branchId: flow.branch_id ?? undefined, departmentId: flow.department_id ?? undefined, manualTrigger: true, stages: rows.map((stage) => ({ key: stage.stage_key, name: stage.name, method: stage.method ?? "", type: stage.step_type, order: stage.sort_order, required: stage.is_required, completionRule: stage.completion_rule ?? "any_doer", allowMultipleDoers: stage.allow_multiple_doers ?? false, requiresUpload: stage.requires_upload ?? false, requiresRemark: stage.requires_remark ?? false, checklist: Array.isArray(stage.checklist_definition) ? stage.checklist_definition as never : [], formTemplateId: stage.form_template_id ?? undefined, assigneeRules: data.assignees.filter((item) => item.fms_stage_id === stage.id && item.assignee_type === "specific_user").map((item) => ({ type: "specific_user" as const, userProfileId: item.user_profile_id ?? undefined, fallbackUserProfileId: item.fallback_user_profile_id ?? undefined, allowNextSelection: item.allow_next_selection })), requiresNextDoerHandoff: stage.requires_next_doer_handoff ?? false, canMoveBackward: stage.can_move_backward ?? false, canReject: stage.can_reject ?? false, canRequestRevision: stage.can_request_revision ?? false, canEscalate: stage.can_escalate ?? false, defaultNextStageKey: stage.default_next_stage_id ? keyById.get(stage.default_next_stage_id) : undefined, branchRules: data.branchRules.filter((item) => item.fms_stage_id === stage.id).map((item) => ({ id: item.id, source: item.source_type as never, sourceKey: item.source_key ?? undefined, operator: item.condition_operator as never, value: item.condition_value ?? undefined, nextStageKey: item.next_stage_id ? keyById.get(item.next_stage_id) : undefined, nextFlowId: item.next_flow_id ?? undefined, order: item.sort_order ?? 0, label: item.label ?? undefined })), parallelTargetStageKeys: stage.parallel_target_stage_ids.map((id) => keyById.get(id)).filter((key): key is string => !!key), joinRule: stage.join_rule ?? undefined, joinRequiredStageKeys: (stage.join_required_stage_ids ?? []).map((id) => keyById.get(id)).filter((key): key is string => !!key), splitToFlowId: stage.split_to_flow_id ?? undefined, sla: stage.planned_time_rule as never })) });
}
