import { useEffect, useMemo, useState } from "react";
import { FMS_STAGE_TYPES, normalizeFmsDefinition, validateFmsDefinition, type FmsFlowDefinition, type FmsStageDefinition } from "@jewelos/core";
import { Button, Field, Notice } from "@/components/ui";
import type { FmsData, FmsFlowRow } from "./api";
import { saveFmsDraft } from "./api";
import { flowToDefinition, newFmsStage } from "./definition";
import { FmsStageEditor } from "./FmsStageEditor";

export function FmsFlowBuilder({ flow, data, duplicate, onClose, onSaved }: { flow: FmsFlowRow | null; data: FmsData; duplicate?: boolean; onClose: () => void; onSaved: () => Promise<void> }) {
  const initial = useMemo(() => { const value = flowToDefinition(flow, data); return duplicate ? { ...value, id: undefined, familyId: undefined, version: 1, lifecycle: "draft" as const, name: `${value.name} (Copy)` } : value; }, [data, duplicate, flow]);
  const [definition, setDefinition] = useState<FmsFlowDefinition>(initial); const [selected, setSelected] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const normalized = useMemo(() => normalizeFmsDefinition(definition), [definition]); const issues = useMemo(() => validateFmsDefinition(normalized), [normalized]); const dirty = JSON.stringify(normalized) !== JSON.stringify(normalizeFmsDefinition(initial));
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
  const updateStage = (index: number, value: FmsStageDefinition) => setDefinition((current) => ({ ...current, stages: current.stages.map((stage, i) => i === index ? value : stage) }));
  const save = async () => { if (issues.length) { setError(issues[0]?.message ?? "Flow is invalid"); return; } setBusy(true); setError(null); try { await saveFmsDraft(duplicate ? null : flow?.id ?? null, normalized); await onSaved(); onClose(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save FMS draft"); } finally { setBusy(false); } };
  return <div className="grid gap-5 lg:grid-cols-[minmax(18rem,.7fr)_minmax(30rem,1.3fr)]"><section className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Flow name"><input className="field" onChange={(e) => setDefinition({ ...definition, name: e.target.value })} value={definition.name} /></Field><Field label="Scope"><select className="field" onChange={(e) => setDefinition({ ...definition, scope: e.target.value as FmsFlowDefinition["scope"], branchId: e.target.value === "tenant" ? undefined : definition.branchId, departmentId: e.target.value === "department" ? definition.departmentId : undefined })} value={definition.scope}><option value="tenant">Tenant global</option><option value="branch">Branch</option><option value="department">Department</option></select></Field></div><Field label="Description"><textarea className="field min-h-20" onChange={(e) => setDefinition({ ...definition, description: e.target.value })} value={definition.description ?? ""} /></Field>{definition.scope !== "tenant" ? <Field label="Branch"><select className="field" onChange={(e) => setDefinition({ ...definition, branchId: e.target.value || undefined, departmentId: undefined })} value={definition.branchId ?? ""}><option value="">Select branch</option>{data.branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></Field> : null}{definition.scope === "department" ? <Field label="Department"><select className="field" onChange={(e) => setDefinition({ ...definition, departmentId: e.target.value || undefined })} value={definition.departmentId ?? ""}><option value="">Select department</option>{data.departments.filter((department) => department.branch_id === definition.branchId).map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select></Field> : null}<Notice>Trigger: Manual only. Versioned event/CRM automation is intentionally unavailable.</Notice>
    <div className="flex flex-wrap gap-2">{FMS_STAGE_TYPES.map((type) => <Button key={type} onClick={() => { const next = newFmsStage(type, definition.stages.length); setDefinition({ ...definition, stages: [...definition.stages, next] }); setSelected(definition.stages.length); }} type="button" variant="secondary">+ {type.replaceAll("_", " ")}</Button>)}</div><ol className="space-y-2">{definition.stages.map((stage, index) => <li key={`${stage.key}-${index}`}><button className={`w-full rounded-xl border p-3 text-left ${selected === index ? "border-gold bg-gold/10" : "border-gold/20"}`} onClick={() => setSelected(index)} type="button"><b>{index + 1}. {stage.name}</b><span className="block text-xs text-soft-grey">{stage.type} · {stage.key}</span></button><div className="mt-1 flex gap-1"><Button disabled={!index} onClick={() => setDefinition({ ...definition, stages: definition.stages.map((item, i, all) => i === index ? all[index - 1]! : i === index - 1 ? all[index]! : item) })} type="button" variant="ghost">Up</Button><Button disabled={index === definition.stages.length - 1} onClick={() => setDefinition({ ...definition, stages: definition.stages.map((item, i, all) => i === index ? all[index + 1]! : i === index + 1 ? all[index]! : item) })} type="button" variant="ghost">Down</Button></div></li>)}</ol></section>
    <section className="space-y-4">{error ? <Notice tone="danger">{error}</Notice> : null}{issues.length ? <Notice tone="danger"><b>Publish validation</b><ul className="mt-2 list-disc pl-5">{issues.map((issue, index) => <li key={`${issue.code}-${index}`}>{issue.stageKey ? `${issue.stageKey}: ` : ""}{issue.message}</li>)}</ul></Notice> : <Notice tone="success">Graph is valid for draft save and server-side publishing validation.</Notice>}{definition.stages[selected] ? <FmsStageEditor data={data} onChange={(value) => updateStage(selected, value)} onDelete={() => { setDefinition({ ...definition, stages: definition.stages.filter((_, index) => index !== selected) }); setSelected(Math.max(0, selected - 1)); }} stage={definition.stages[selected]!} stages={definition.stages} /> : <Notice>Add a stage to begin building.</Notice>}<div className="sticky bottom-0 flex gap-2 bg-obsidian/95 py-3"><Button disabled={busy || issues.length > 0} onClick={() => void save()}>{busy ? "Saving…" : "Save draft"}</Button><Button onClick={() => { if (!dirty || window.confirm("Discard unsaved FMS changes?")) onClose(); }} type="button" variant="ghost">Cancel</Button></div></section></div>;
}
