import { FMS_ASSIGNEE_TYPES, FMS_BRANCH_OPERATORS, type FmsStageDefinition } from "@jewelos/core";
import { Button, Field } from "@/components/ui";
import type { FmsData } from "./api";

export function FmsStageEditor({ stage, stages, data, onChange, onDelete }: { stage: FmsStageDefinition; stages: readonly FmsStageDefinition[]; data: FmsData; onChange: (value: FmsStageDefinition) => void; onDelete: () => void }) {
  const update = (patch: Partial<FmsStageDefinition>) => onChange({ ...stage, ...patch });
  const others = stages.filter((item) => item.key !== stage.key);
  const automatic = ["branch", "parallel_start", "parallel_join", "notification", "end"].includes(stage.type);
  const canChooseNext = !["branch", "parallel_start", "end"].includes(stage.type);
  return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2"><Field label="Stable stage key"><input className="field" onChange={(event) => update({ key: event.target.value.toLowerCase().replace(/[^a-z0-9_]/g, "_") })} value={stage.key} /></Field><Field label="Stage name"><input className="field" onChange={(event) => update({ name: event.target.value })} value={stage.name} /></Field></div><Field label="Instructions"><textarea className="field min-h-20" onChange={(event) => update({ method: event.target.value })} placeholder="Tell the assignee what success looks like." value={stage.method ?? ""} /></Field><div className="grid gap-3 sm:grid-cols-3"><Field label="Completion"><select className="field" disabled={automatic} onChange={(event) => update({ completionRule: event.target.value as FmsStageDefinition["completionRule"] })} value={stage.completionRule}><option value="any_doer">Any doer</option><option value="all_doers">All doers</option><option value="manager_approval">Manager approval</option></select></Field><Field label="SLA minutes"><input className="field" min="0" onChange={(event) => update({ sla: { ...stage.sla, minutes: Number(event.target.value) } })} type="number" value={stage.sla.minutes} /></Field><Field label="Escalate after"><input className="field" min="0" onChange={(event) => update({ sla: { ...stage.sla, escalateAfterMinutes: Number(event.target.value) || undefined } })} type="number" value={stage.sla.escalateAfterMinutes ?? ""} /></Field></div>
    {!automatic ? <section className="rounded-xl border border-gold/20 p-3"><h4 className="mb-2 font-semibold">Who completes this?</h4>{stage.assigneeRules.map((rule, index) => <div className="mb-2 grid gap-2 sm:grid-cols-3" key={`${rule.type}-${index}`}><select className="field" onChange={(event) => update({ assigneeRules: stage.assigneeRules.map((item, itemIndex) => itemIndex === index ? { type: event.target.value as never } : item) })} value={rule.type}>{FMS_ASSIGNEE_TYPES.map((type) => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select>{rule.type === "specific_user" ? <select className="field" onChange={(event) => update({ assigneeRules: stage.assigneeRules.map((item, itemIndex) => itemIndex === index ? { ...item, userProfileId: event.target.value } : item) })} value={rule.userProfileId ?? ""}><option value="">Select an eligible user</option>{data.users.filter((user) => user.working_status === "active" && user.is_login_enabled).map((user) => <option key={user.id} value={user.id}>{user.employee_name}</option>)}</select> : rule.type === "role" ? <select className="field" onChange={(event) => update({ assigneeRules: stage.assigneeRules.map((item, itemIndex) => itemIndex === index ? { ...item, role: event.target.value as never } : item) })} value={rule.role ?? "staff"}>{["super_admin", "admin", "manager", "crm", "staff", "doer"].map((role) => <option key={role} value={role}>{role}</option>)}</select> : <span className="self-center text-xs text-soft-grey">Resolved from current organization data</span>}<Button onClick={() => update({ assigneeRules: stage.assigneeRules.filter((_, itemIndex) => itemIndex !== index) })} type="button" variant="danger">Remove</Button></div>)}<Button onClick={() => update({ assigneeRules: [...stage.assigneeRules, { type: "reporter" }] })} type="button" variant="secondary">Add assignee rule</Button></section> : null}
    {stage.type === "form" ? <section className="rounded-xl border border-success/30 bg-success/5 p-3"><h4 className="mb-1 font-semibold text-success">Required Form</h4><p className="mb-3 text-xs text-soft-grey">The exact published version is pinned when this FMS is published.</p><select className="field" onChange={(event) => update({ formTemplateId: event.target.value || undefined })} value={stage.formTemplateId ?? ""}><option value="">Select the required Form</option>{data.forms.map((form) => <option key={form.id} value={form.id}>{form.name} · v{form.version}</option>)}</select></section> : null}
    {canChooseNext ? <Field label="Next stage"><StageSelect others={others} value={stage.defaultNextStageKey} onChange={(value) => update({ defaultNextStageKey: value })} /></Field> : null}
    {stage.type === "branch" ? <section className="rounded-xl border border-gold/20 p-3"><h4 className="mb-1 font-semibold">Decision routes</h4><p className="mb-3 text-xs text-soft-grey">For Form-driven routing, enter the prior Form field’s stable key. Keep exactly one final Default route.</p>{stage.branchRules.map((rule, index) => <div className="mb-3 grid gap-2 sm:grid-cols-5" key={rule.id}><select className="field" onChange={(event) => update({ branchRules: stage.branchRules.map((item, itemIndex) => itemIndex === index ? { ...item, source: event.target.value as never } : item) })} value={rule.source}><option value="outcome">Outcome</option><option value="context">Process data</option><option value="form_answer">Form answer</option></select><input className="field" disabled={rule.source === "outcome"} onChange={(event) => update({ branchRules: stage.branchRules.map((item, itemIndex) => itemIndex === index ? { ...item, sourceKey: event.target.value } : item) })} placeholder="stable field key" value={rule.sourceKey ?? ""} /><select className="field" onChange={(event) => update({ branchRules: stage.branchRules.map((item, itemIndex) => itemIndex === index ? { ...item, operator: event.target.value as never } : item) })} value={rule.operator}>{FMS_BRANCH_OPERATORS.map((operator) => <option key={operator} value={operator}>{operator}</option>)}</select><input className="field" disabled={rule.operator === "default" || rule.operator === "not_empty"} onChange={(event) => update({ branchRules: stage.branchRules.map((item, itemIndex) => itemIndex === index ? { ...item, value: event.target.value } : item) })} placeholder="expected value" value={String(rule.value ?? "")} /><StageSelect others={others} value={rule.nextStageKey} onChange={(value) => update({ branchRules: stage.branchRules.map((item, itemIndex) => itemIndex === index ? { ...item, nextStageKey: value } : item) })} /></div>)}<Button onClick={() => update({ branchRules: [...stage.branchRules, { id: crypto.randomUUID(), source: "outcome", operator: "default", order: stage.branchRules.length }] })} type="button" variant="secondary">Add route</Button></section> : null}
    {stage.type === "parallel_start" ? <section><h4 className="mb-2 font-semibold">Parallel targets</h4>{others.map((item) => <label className="mr-3 inline-block text-sm" key={item.key}><input checked={stage.parallelTargetStageKeys.includes(item.key)} onChange={(event) => update({ parallelTargetStageKeys: event.target.checked ? [...stage.parallelTargetStageKeys, item.key] : stage.parallelTargetStageKeys.filter((key) => key !== item.key) })} type="checkbox" /> {item.name}</label>)}</section> : null}
    {stage.type === "parallel_join" ? <Field label="After join"><StageSelect others={others} value={stage.defaultNextStageKey} onChange={(value) => update({ defaultNextStageKey: value })} /></Field> : null}
    {!automatic ? <div className="flex flex-wrap gap-3 text-sm">{([{ key: "requiresUpload", label: "Require evidence" }, { key: "requiresRemark", label: "Require remark" }, { key: "requiresNextDoerHandoff", label: "Choose next assignee" }, { key: "canReject", label: "Can reject" }, { key: "canRequestRevision", label: "Can request revision" }] as const).map(({ key, label }) => <label key={key}><input checked={stage[key]} onChange={(event) => update({ [key]: event.target.checked })} type="checkbox" /> {label}</label>)}</div> : null}<Button onClick={onDelete} type="button" variant="danger">Delete stage</Button></div>;
}

function StageSelect({ others, value, onChange }: { others: readonly FmsStageDefinition[]; value?: string | undefined; onChange: (value: string | undefined) => void }) { return <select className="field" onChange={(event) => onChange(event.target.value || undefined)} value={value ?? ""}><option value="">No next stage</option>{others.map((item) => <option key={item.key} value={item.key}>{item.name}</option>)}</select>; }
