import { describe, expect, it } from "vitest";
import { calculateFmsDelay, calculateFmsProgress, deriveFmsTransitionCapability, evaluateFmsBranchRule, fmsStatusLabel, isFmsCompletionSatisfied, isFmsJoinReady, normalizeFmsDefinition, reachableFmsStageKeys, resolveFmsBranch, validateFmsAssignmentCandidate, validateFmsDefinition, type FmsFlowDefinition, type FmsStageDefinition } from ".";

const stage = (patch: Partial<FmsStageDefinition> & Pick<FmsStageDefinition, "key" | "name" | "type" | "order">): FmsStageDefinition => ({ required: true, completionRule: patch.type === "approval" ? "manager_approval" : "any_doer", allowMultipleDoers: false, requiresUpload: false, requiresRemark: false, checklist: [], assigneeRules: ["branch", "parallel_start", "parallel_join", "notification", "end"].includes(patch.type) ? [] : [{ type: "reporter" }], requiresNextDoerHandoff: false, canMoveBackward: false, canReject: false, canRequestRevision: false, canEscalate: false, branchRules: [], parallelTargetStageKeys: [], joinRequiredStageKeys: [], sla: { dueDate: "2099-12-31" }, ...patch });
const flow = (stages: FmsStageDefinition[]): FmsFlowDefinition => ({ name: "Order flow", description: "test", scope: "tenant", manualTrigger: true, stages });
const formId = "00000000-0000-4000-8000-000000000001";
const good = () => flow([stage({ key: "start_form", name: "Start form", type: "form", order: 0, formTemplateId: formId, defaultNextStageKey: "done" }), stage({ key: "done", name: "Done", type: "task", order: 1 })]);

describe("FMS definitions", () => {
  it("normalizes deterministic stage order and text", () => { const value = normalizeFmsDefinition(flow([stage({ key: " DONE ", name: " Done ", type: "task", order: 9 }), stage({ key: " START_FORM ", name: " Start ", type: "form", formTemplateId: formId, order: 2, defaultNextStageKey: " DONE " })])); expect(value.stages.map((item) => [item.key, item.order])).toEqual([["start_form", 0], ["done", 1]]); expect(value.stages[0]?.defaultNextStageKey).toBe("done"); });
  it("strips retired per-stage fallback users from newly normalized revisions", () => { const value = normalizeFmsDefinition(flow([stage({ key: "form", name: "Form", type: "form", formTemplateId: formId, order: 0, assigneeRules: [{ type: "specific_user", userProfileId: formId, fallbackUserProfileId: "00000000-0000-4000-8000-000000000002" }] })])); expect(value.stages[0]?.assigneeRules[0]?.fallbackUserProfileId).toBeUndefined(); });
  it("accepts a valid linear graph", () => expect(validateFmsDefinition(good())).toEqual([]));
  it("rejects an empty flow", () => expect(validateFmsDefinition(flow([])).map((item) => item.code)).toContain("empty_flow"));
  it("rejects duplicate identities", () => expect(validateFmsDefinition(flow([stage({ key: "same", name: "A", type: "form", formTemplateId: formId, order: 0, defaultNextStageKey: "same" }), stage({ key: "same", name: "B", type: "task", order: 1 })])).some((item) => item.code === "invalid_stage_key")).toBe(true));
  it("rejects dangling references", () => expect(validateFmsDefinition(flow([stage({ key: "start_form", name: "A", type: "form", formTemplateId: formId, order: 0, defaultNextStageKey: "missing" })])).some((item) => item.code === "dangling_reference")).toBe(true));
  it("rejects unreachable stages", () => expect(validateFmsDefinition(flow([...good().stages, stage({ key: "island", name: "Island", type: "task", order: 2 })])).some((item) => item.stageKey === "island" && item.code === "unreachable_stage")).toBe(true));
  it("rejects unsupported cycles", () => expect(validateFmsDefinition(flow([stage({ key: "a", name: "A", type: "form", formTemplateId: formId, order: 0, defaultNextStageKey: "b" }), stage({ key: "b", name: "B", type: "task", order: 1, defaultNextStageKey: "a" })])).some((item) => item.code === "unsupported_cycle")).toBe(true));
  it("accepts a leaf step as implicit completion", () => expect(validateFmsDefinition(flow([stage({ key: "start_form", name: "A", type: "form", formTemplateId: formId, order: 0 })]))).toEqual([]));
  it("rejects legacy explicit end nodes", () => expect(validateFmsDefinition(flow([stage({ key: "start_form", name: "A", type: "form", formTemplateId: formId, order: 0, defaultNextStageKey: "done" }), stage({ key: "done", name: "Done", type: "end", order: 1 })])).some((item) => item.code === "legacy_end_stage")).toBe(true));
  it("requires the first stage to be a form", () => expect(validateFmsDefinition(flow([stage({ key: "task", name: "Task", type: "task", order: 0 })])).some((item) => item.code === "first_stage_must_be_form")).toBe(true));
  it("requires a final default branch", () => expect(validateFmsDefinition(flow([stage({ key: "start_form", name: "Form", type: "form", formTemplateId: formId, order: 0, defaultNextStageKey: "branch" }), stage({ key: "branch", name: "Route", type: "branch", order: 1, branchRules: [{ id: "r", source: "outcome", operator: "equals", value: "yes", nextStageKey: "done", order: 0 }] }), stage({ key: "done", name: "Done", type: "task", order: 2 })])).some((item) => item.code === "invalid_branch")).toBe(true));
  it("requires parallel targets", () => expect(validateFmsDefinition(flow([stage({ key: "start_form", name: "Form", type: "form", formTemplateId: formId, order: 0, defaultNextStageKey: "split" }), stage({ key: "split", name: "Split", type: "parallel_start", order: 1 }), stage({ key: "done", name: "Done", type: "task", order: 2 })])).some((item) => item.code === "invalid_parallel")).toBe(true));
  it("validates completion rules", () => expect(validateFmsDefinition(flow([stage({ key: "start_form", name: "Form", type: "form", formTemplateId: formId, order: 0, defaultNextStageKey: "done" }), stage({ key: "done", name: "Done", type: "task", order: 1, completionRule: "all_doers" })])).some((item) => item.code === "incompatible_completion_rule")).toBe(true));
  it("validates exact form linkage", () => expect(validateFmsDefinition(flow([stage({ key: "form", name: "Form", type: "form", order: 0 })])).some((item) => item.code === "missing_form")).toBe(true));
  it("keeps forms optional after the initial details step", () => expect(validateFmsDefinition(flow([stage({ key: "start_form", name: "Start", type: "form", formTemplateId: formId, order: 0, defaultNextStageKey: "follow_up" }), stage({ key: "follow_up", name: "Optional later form", type: "form", order: 1 })]))).toEqual([]));
  it("requires a calendar completion date", () => expect(validateFmsDefinition(flow([stage({ key: "form", name: "Form", type: "form", formTemplateId: formId, order: 0, sla: { dueDate: "" } })])).some((item) => item.code === "invalid_deadline")).toBe(true));
  it("does not require a deadline for an automatic notification", () => expect(validateFmsDefinition(flow([stage({ key: "form", name: "Form", type: "form", formTemplateId: formId, order: 0, defaultNextStageKey: "notice" }), stage({ key: "notice", name: "Notify", type: "notification", order: 1, sla: { dueDate: "" } })]))).toEqual([]));
  it("accepts a later Yes or No decision and a conditional step", () => expect(validateFmsDefinition(flow([stage({ key: "form", name: "Form", type: "form", formTemplateId: formId, order: 0, defaultNextStageKey: "decision" }), stage({ key: "decision", name: "Decide", type: "task", order: 1, defaultNextStageKey: "follow_up", sla: { dueDate: "2099-12-31", decisionMode: "yes_no" } }), stage({ key: "follow_up", name: "Follow up", type: "task", order: 2, sla: { dueDate: "2099-12-31", conditional: { decisionStageKey: "decision", outcome: "yes" } } })]))).toEqual([]));
  it("normalizes legacy Yes/No decisions into dynamic options and minute TAT", () => {
    const decision = normalizeFmsDefinition(flow([stage({ key: "form", name: "Form", type: "form", formTemplateId: formId, order: 0, defaultNextStageKey: "decision" }), stage({ key: "decision", name: "Decide", type: "task", order: 1, sla: { dueDate: "", decisionMode: "yes_no", timingMethod: "tat_hours", tatHours: 2 } })])).stages[1]!;
    expect(decision.sla.decisionOptions).toEqual([{ key: "yes", label: "Yes" }, { key: "no", label: "No" }]);
    expect(decision.sla.tatMinutes).toBe(120);
  });
  it("allows a human stage to opt out of its deadline", () => expect(validateFmsDefinition(flow([stage({ key: "form", name: "Form", type: "form", formTemplateId: formId, order: 0, sla: { dueDate: "", deadlineEnabled: false } })]))).toEqual([]));
  it("rejects a dynamic decision condition whose option was removed", () => expect(validateFmsDefinition(flow([stage({ key: "form", name: "Form", type: "form", formTemplateId: formId, order: 0, defaultNextStageKey: "decision" }), stage({ key: "decision", name: "Decide", type: "task", order: 1, sla: { dueDate: "2099-12-31", decisionMode: "decision", decisionOptions: [{ key: "connected", label: "Connected" }] } }), stage({ key: "follow_up", name: "Follow up", type: "task", order: 2, sla: { dueDate: "2099-12-31", conditional: { decisionStageKey: "decision", decisionOptionKey: "removed" } } })]))).toContainEqual(expect.objectContaining({ code: "invalid_conditional" })));
  it("rejects a condition that does not reference an earlier decision", () => expect(validateFmsDefinition(flow([stage({ key: "form", name: "Form", type: "form", formTemplateId: formId, order: 0, defaultNextStageKey: "follow_up" }), stage({ key: "follow_up", name: "Follow up", type: "task", order: 1, sla: { dueDate: "2099-12-31", conditional: { decisionStageKey: "form", outcome: "yes" } } })])).some((item) => item.code === "invalid_conditional")).toBe(true));
  it("drops retired Status conditions while preserving decision-only routing", () => {
    const legacy = flow([stage({ key: "form", name: "Form", type: "form", formTemplateId: formId, order: 0, defaultNextStageKey: "follow_up" }), stage({ key: "follow_up", name: "Follow up", type: "task", order: 1, sla: { dueDate: "2099-12-31", conditional: { field: "status", operator: "equals", value: "interested" } as never } })]);
    expect(normalizeFmsDefinition(legacy).stages[1]?.sla.conditional).toBeUndefined();
  });
  it("validates each timing method", () => { expect(validateFmsDefinition(flow([stage({ key: "form", name: "Form", type: "form", formTemplateId: formId, order: 0, sla: { timingMethod: "tat_hours", dueDate: "", tatHours: 3 } })]))).toEqual([]); expect(validateFmsDefinition(flow([stage({ key: "form", name: "Form", type: "form", formTemplateId: formId, order: 0, sla: { timingMethod: "specific_time", dueDate: "2099-12-31", clockTime: "25:00" } })])).some((item) => item.code === "invalid_deadline")).toBe(true); });
  it("returns graph reachability", () => expect([...reachableFmsStageKeys(good())]).toEqual(["start_form", "done"]));
});

describe("FMS runtime helpers", () => {
  const base = { id: "r", source: "outcome" as const, order: 0, nextStageKey: "done" };
  it.each([["equals", "ok", "ok", true], ["not_equals", "a", "b", true], ["contains", "gold ring", "gold", true], ["greater_than", 3, 2, true], ["greater_than_or_equal", 2, 2, true], ["less_than", 2, 3, true], ["less_than_or_equal", 2, 2, true], ["in", "a", ["a", "b"], true], ["not_empty", "x", undefined, true]])("evaluates %s", (operator, actual, value, expected) => expect(evaluateFmsBranchRule({ ...base, operator: operator as never, value }, actual)).toBe(expected));
  it("uses deterministic first-match routing", () => expect(resolveFmsBranch([{ ...base, operator: "equals", value: "yes", nextStageKey: "yes" }, { ...base, id: "default", operator: "default", order: 1, nextStageKey: "no" }], { outcome: "no" })?.nextStageKey).toBe("no"));
  it("supports all joins", () => expect(isFmsJoinReady("all", [{ key: "a", completed: true }, { key: "b", completed: true }])).toBe(true));
  it("supports any joins", () => expect(isFmsJoinReady("any", [{ key: "a", completed: false }, { key: "b", completed: true }])).toBe(true));
  it("supports specific joins", () => expect(isFmsJoinReady("specific", [{ key: "a", completed: true }, { key: "b", completed: false }], ["a"])).toBe(true));
  it("evaluates all-doer completion", () => expect(isFmsCompletionSatisfied("all_doers", [{ actorId: "a", completed: true }, { actorId: "b", completed: true }])).toBe(true));
  it("evaluates any-doer completion", () => expect(isFmsCompletionSatisfied("any_doer", [{ actorId: "a", completed: false }, { actorId: "b", completed: true }])).toBe(true));
  it("requires an elevated manager approval", () => { expect(isFmsCompletionSatisfied("manager_approval", [{ actorId: "a", completed: true }], "staff")).toBe(false); expect(isFmsCompletionSatisfied("manager_approval", [{ actorId: "a", completed: true }], "manager")).toBe(true); });
  it("validates assignment scope and working state", () => { const candidate = { id: "a", tenantId: "t", branchId: "b", departmentId: "d", role: "staff" as const, active: true, loginEnabled: true }; expect(validateFmsAssignmentCandidate(candidate, { tenantId: "t", branchId: "b", departmentId: "d" })).toBe(true); expect(validateFmsAssignmentCandidate({ ...candidate, active: false }, { tenantId: "t" })).toBe(false); });
  it("derives doer and elevated capabilities", () => { const item = stage({ key: "approve", name: "Approve", type: "approval", order: 0, canReject: true, canEscalate: true }); expect(deriveFmsTransitionCapability({ viewerId: "m", viewerRole: "manager", assignedIds: [], instanceStatus: "active", stageStatus: "in_review", stage: item }).canApprove).toBe(true); expect(deriveFmsTransitionCapability({ viewerId: "d", viewerRole: "doer", assignedIds: ["d"], instanceStatus: "on_hold", stageStatus: "in_progress", stage: item }).canApprove).toBe(false); });
  it("calculates required-stage progress", () => expect(calculateFmsProgress([{ required: true, status: "completed" }, { required: true, status: "in_progress" }, { required: false, status: "pending" }])).toEqual({ completed: 1, total: 2, percent: 50 }));
  it("calculates non-negative delay", () => { expect(calculateFmsDelay("2026-01-01T01:00:00Z", "2026-01-01T01:30:00Z")).toEqual({ delayMinutes: 30, overdue: true }); expect(calculateFmsDelay("2026-01-01T01:00:00Z", "2026-01-01T00:30:00Z")).toEqual({ delayMinutes: 0, overdue: false }); });
  it("formats safe labels", () => expect(fmsStatusLabel("in_progress")).toBe("In Progress"));
});
