import { describe, expect, it } from "vitest";
import { calculateFmsDelay, calculateFmsPlannedAt, calculateFmsProgress, deriveFmsTransitionCapability, evaluateFmsBranchRule, fmsStatusLabel, isFmsCompletionSatisfied, isFmsJoinReady, normalizeFmsDefinition, reachableFmsStageKeys, resolveFmsBranch, validateFmsAssignmentCandidate, validateFmsDefinition, type FmsFlowDefinition, type FmsStageDefinition } from ".";

const stage = (patch: Partial<FmsStageDefinition> & Pick<FmsStageDefinition, "key" | "name" | "type" | "order">): FmsStageDefinition => ({ required: true, completionRule: patch.type === "approval" ? "manager_approval" : "any_doer", allowMultipleDoers: false, requiresUpload: false, requiresRemark: false, checklist: [], assigneeRules: ["branch", "parallel_start", "parallel_join", "notification", "end"].includes(patch.type) ? [] : [{ type: "reporter" }], requiresNextDoerHandoff: false, canMoveBackward: false, canReject: false, canRequestRevision: false, canEscalate: false, branchRules: [], parallelTargetStageKeys: [], joinRequiredStageKeys: [], sla: { minutes: 60 }, ...patch });
const flow = (stages: FmsStageDefinition[]): FmsFlowDefinition => ({ name: "Order flow", description: "test", scope: "tenant", manualTrigger: true, stages });
const good = () => flow([stage({ key: "start", name: "Start", type: "task", order: 0, defaultNextStageKey: "done" }), stage({ key: "done", name: "Done", type: "end", order: 1 })]);

describe("FMS definitions", () => {
  it("normalizes deterministic stage order and text", () => { const value = normalizeFmsDefinition(flow([stage({ key: " DONE ", name: " Done ", type: "end", order: 9 }), stage({ key: " START ", name: " Start ", type: "task", order: 2, defaultNextStageKey: " DONE " })])); expect(value.stages.map((item) => [item.key, item.order])).toEqual([["start", 0], ["done", 1]]); expect(value.stages[0]?.defaultNextStageKey).toBe("done"); });
  it("accepts a valid linear graph", () => expect(validateFmsDefinition(good())).toEqual([]));
  it("rejects an empty flow", () => expect(validateFmsDefinition(flow([])).map((item) => item.code)).toContain("empty_flow"));
  it("rejects duplicate identities", () => expect(validateFmsDefinition(flow([stage({ key: "same", name: "A", type: "task", order: 0, defaultNextStageKey: "same" }), stage({ key: "same", name: "B", type: "end", order: 1 })])).some((item) => item.code === "invalid_stage_key")).toBe(true));
  it("rejects dangling references", () => expect(validateFmsDefinition(flow([stage({ key: "start", name: "A", type: "task", order: 0, defaultNextStageKey: "missing" })])).some((item) => item.code === "dangling_reference")).toBe(true));
  it("rejects unreachable stages", () => expect(validateFmsDefinition(flow([...good().stages, stage({ key: "island", name: "Island", type: "task", order: 2 })])).some((item) => item.stageKey === "island" && item.code === "unreachable_stage")).toBe(true));
  it("rejects unsupported cycles", () => expect(validateFmsDefinition(flow([stage({ key: "a", name: "A", type: "task", order: 0, defaultNextStageKey: "b" }), stage({ key: "b", name: "B", type: "task", order: 1, defaultNextStageKey: "a" })])).some((item) => item.code === "unsupported_cycle")).toBe(true));
  it("requires a reachable end", () => expect(validateFmsDefinition(flow([stage({ key: "start", name: "A", type: "task", order: 0 })])).some((item) => item.code === "missing_end_path")).toBe(true));
  it("requires a final default branch", () => expect(validateFmsDefinition(flow([stage({ key: "branch", name: "Route", type: "branch", order: 0, branchRules: [{ id: "r", source: "outcome", operator: "equals", value: "yes", nextStageKey: "done", order: 0 }] }), stage({ key: "done", name: "Done", type: "end", order: 1 })])).some((item) => item.code === "invalid_branch")).toBe(true));
  it("requires parallel targets", () => expect(validateFmsDefinition(flow([stage({ key: "split", name: "Split", type: "parallel_start", order: 0 }), stage({ key: "done", name: "Done", type: "end", order: 1 })])).some((item) => item.code === "invalid_parallel")).toBe(true));
  it("requires specific join prerequisites", () => expect(validateFmsDefinition(flow([stage({ key: "join", name: "Join", type: "parallel_join", order: 0, joinRule: "specific", defaultNextStageKey: "done" }), stage({ key: "done", name: "Done", type: "end", order: 1 })])).some((item) => item.code === "invalid_join")).toBe(true));
  it("validates completion rules", () => expect(validateFmsDefinition(flow([stage({ key: "a", name: "A", type: "task", order: 0, completionRule: "all_doers", defaultNextStageKey: "done" }), stage({ key: "done", name: "Done", type: "end", order: 1 })])).some((item) => item.code === "incompatible_completion_rule")).toBe(true));
  it("validates exact form linkage", () => expect(validateFmsDefinition(flow([stage({ key: "form", name: "Form", type: "form", order: 0, defaultNextStageKey: "done" }), stage({ key: "done", name: "Done", type: "end", order: 1 })])).some((item) => item.code === "missing_form")).toBe(true));
  it("returns graph reachability", () => expect([...reachableFmsStageKeys(good())]).toEqual(["start", "done"]));
});

describe("FMS runtime helpers", () => {
  const base = { id: "r", source: "outcome" as const, order: 0, nextStageKey: "done" };
  it.each([["equals", "ok", "ok", true], ["not_equals", "a", "b", true], ["contains", "gold ring", "gold", true], ["greater_than", 3, 2, true], ["greater_than_or_equal", 2, 2, true], ["less_than", 2, 3, true], ["less_than_or_equal", 2, 2, true], ["in", "a", ["a", "b"], true], ["not_empty", "x", undefined, true]])("evaluates %s", (operator, actual, value, expected) => expect(evaluateFmsBranchRule({ ...base, operator: operator as never, value }, actual)).toBe(expected));
  it("uses deterministic first-match routing", () => expect(resolveFmsBranch([{ ...base, operator: "equals", value: "yes", nextStageKey: "yes" }, { ...base, id: "default", operator: "default", order: 1, nextStageKey: "no" }], { outcome: "no" })?.nextStageKey).toBe("no"));
  it("supports all joins", () => expect(isFmsJoinReady("all", [{ key: "a", completed: true }, { key: "b", completed: true }])).toBe(true));
  it("supports any joins", () => expect(isFmsJoinReady("any", [{ key: "a", completed: false }, { key: "b", completed: true }])).toBe(true));
  it("supports specific joins", () => expect(isFmsJoinReady("specific", [{ key: "a", completed: true }, { key: "b", completed: false }], ["a"])).toBe(true));
  it("evaluates all-doer completion", () => expect(isFmsCompletionSatisfied("all_doers", [{ actorId: "a", completed: true }, { actorId: "b", completed: true }])).toBe(true));
  it("evaluates any-doer completion", () => expect(isFmsCompletionSatisfied("any_doer", [{ actorId: "a", completed: false }, { actorId: "b", completed: true }])).toBe(true));
  it("requires an elevated manager approval", () => { expect(isFmsCompletionSatisfied("manager_approval", [{ actorId: "a", completed: true }], "staff")).toBe(false); expect(isFmsCompletionSatisfied("manager_approval", [{ actorId: "a", completed: true }], "manager")).toBe(true); });
  it("validates assignment scope and working state", () => { const candidate = { id: "a", tenantId: "t", branchId: "b", departmentId: "d", role: "staff" as const, active: true, loginEnabled: true }; expect(validateFmsAssignmentCandidate(candidate, { tenantId: "t", branchId: "b", departmentId: "d" })).toBe(true); expect(validateFmsAssignmentCandidate({ ...candidate, active: false }, { tenantId: "t" })).toBe(false); });
  it("derives doer and elevated capabilities", () => { const item = stage({ key: "approve", name: "Approve", type: "approval", order: 0, canReject: true, canEscalate: true }); expect(deriveFmsTransitionCapability({ viewerId: "m", viewerRole: "manager", assignedIds: [], instanceStatus: "active", stageStatus: "in_review", stage: item }).canApprove).toBe(true); expect(deriveFmsTransitionCapability({ viewerId: "d", viewerRole: "doer", assignedIds: ["d"], instanceStatus: "on_hold", stageStatus: "in_progress", stage: item }).canApprove).toBe(false); });
  it("calculates required-stage progress", () => expect(calculateFmsProgress([{ required: true, status: "completed" }, { required: true, status: "in_progress" }, { required: false, status: "pending" }])).toEqual({ completed: 1, total: 2, percent: 50 }));
  it("calculates SLA timestamps", () => expect(calculateFmsPlannedAt("2026-01-01T00:00:00Z", 60)).toBe("2026-01-01T01:00:00.000Z"));
  it("calculates non-negative delay", () => { expect(calculateFmsDelay("2026-01-01T01:00:00Z", "2026-01-01T01:30:00Z")).toEqual({ delayMinutes: 30, overdue: true }); expect(calculateFmsDelay("2026-01-01T01:00:00Z", "2026-01-01T00:30:00Z")).toEqual({ delayMinutes: 0, overdue: false }); });
  it("formats safe labels", () => expect(fmsStatusLabel("in_progress")).toBe("In Progress"));
});
