import {useCallback,useEffect,useMemo,useState} from "react";
import {REPORT_CATALOG,parseReportFilters,reportsForRole,type ReportDefinition,type ReportFilters} from "@jewelos/core";
import {Download,RefreshCw,RotateCcw,Square,Upload} from "lucide-react";
import {useAuth} from "@/auth/AuthContext";
import {Button} from "@/components/ui";
import {ErrorPanel,LoadingPanels,PageHeading,PageSurface,Panel,StatusDot} from "@/features/analytics/components";
import {fetchReportingOptions,type ReportingOptions} from "@/features/analytics/api";
import {cancelExport,fetchReport,requestExport,retryExport,signedExportUrl,type ReportPayload} from "./api";
import {titleCase} from "@/lib/format";

const iso=(date:Date)=>date.toISOString().slice(0,10);const today=new Date();const monthAgo=new Date(Date.now()-29*86_400_000);
function initialParams(definition:ReportDefinition){const params=new URLSearchParams(window.location.search);if(!params.get("from"))params.set("from",iso(monthAgo));if(!params.get("to"))params.set("to",iso(today));if(!params.get("page"))params.set("page","1");if(!params.get("page_size"))params.set("page_size","25");try{return parseReportFilters(params,definition);}catch{return parseReportFilters({from:iso(monthAgo),to:iso(today),page:"1",page_size:"25"},definition);}}
function writeUrl(report:string,filters:ReportFilters){const params=new URLSearchParams({report});for(const [key,value] of Object.entries(filters))if(value!==undefined)params.set(key,String(value));window.history.replaceState({},"",`${window.location.pathname}?${params}`);}
function renderCell(value:unknown){if(value===null||value===undefined||value==="")return "—";if(typeof value==="boolean")return value?"Yes":"No";if(typeof value==="number")return Number.isInteger(value)?value.toLocaleString("en-IN"):value.toFixed(1);const text=String(value);if(/^\d{4}-\d{2}-\d{2}T/.test(text))return new Date(text).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"});return titleCase(text);}

export function ReportsView(){
  const {profile}=useAuth();
  const catalog=useMemo(()=>reportsForRole(profile!.user_role),[profile]);
  const requested=new URLSearchParams(window.location.search).get("report");
  const [definition,setDefinition]=useState(()=>catalog.find((item)=>item.key===requested)??catalog[0]!);
  const [filters,setFilters]=useState<ReportFilters>(()=>initialParams(definition));
  const [data,setData]=useState<ReportPayload|null>(null);const [history,setHistory]=useState<ReportPayload|null>(null);
  const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);const [exporting,setExporting]=useState(false);
  const [options,setOptions]=useState<ReportingOptions>({branches:[],departments:[]});
  const elevated=["super_admin","admin","manager","hr"].includes(profile!.user_role);
  const canSelectBranch=["super_admin","admin"].includes(profile!.user_role);
  useEffect(()=>{if(elevated)void fetchReportingOptions().then(setOptions);},[elevated]);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const [preview,exports]=await Promise.all([fetchReport(definition.key,filters),fetchReport("export_history",{...filters,page:1,page_size:25})]);setData(preview);setHistory(exports);}catch(error){setError(error instanceof Error?error.message:"Report request failed");}finally{setLoading(false);}},[definition,filters]);
  useEffect(()=>{writeUrl(definition.key,filters);void load();},[definition,filters,load]);
  useEffect(()=>{if(!history?.rows.some((row)=>row.status==="queued"||row.status==="processing"))return;const timer=window.setInterval(()=>void load(),5000);return()=>window.clearInterval(timer);},[history,load]);
  const changeReport=(key:string)=>{const next=REPORT_CATALOG.find((item)=>item.key===key);if(!next)return;setDefinition(next);setFilters(initialParams(next));};
  const changeFilter=(key:keyof ReportFilters,value:string|number|undefined)=>setFilters((current)=>({...current,[key]:value||undefined,page:key==="page"?Number(value):1}));
  const doExport=async()=>{setExporting(true);setMessage(null);try{await requestExport(definition.key,filters);setMessage("CSV export queued. Progress appears in export history.");await load();}catch(error){setError(error instanceof Error?error.message:"Export request failed");}finally{setExporting(false);}};
  const lifecycle=async(action:"cancel"|"retry"|"download",id:string)=>{setMessage(null);try{if(action==="cancel")await cancelExport(id);else if(action==="retry")await retryExport(id);else window.location.assign(await signedExportUrl(id));setMessage(action==="download"?"Short-lived download authorized.":`Export ${action} request accepted.`);await load();}catch(error){setError(error instanceof Error?error.message:"Export action failed");}};
  const totalPages=Math.max(1,Math.ceil((data?.total??0)/filters.page_size));
  const scopedDepartments=options.departments.filter((item)=>!filters.branch_id||item.branch_id===null||item.branch_id===filters.branch_id);
  return <PageSurface>
    <PageHeading title="Reports & Exports" description="Fixed, role-authorized reports with bounded previews and private asynchronous CSV exports." actions={definition.exportEligible?<Button disabled={exporting} onClick={()=>void doExport()}><Upload/>{exporting?"Queuing…":"Request CSV export"}</Button>:undefined}/>
    {message?<p aria-live="polite" className="mb-4 rounded-lg border border-success/40 bg-task-bg p-3 text-sm text-success">{message}</p>:null}
    <div className="mb-4 rounded-xl border border-task-border bg-task-bg p-4">
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <label className="sm:col-span-2"><span className="mb-1 block text-xs font-medium text-task-text-muted">Report</span><select className="task-field" onChange={(event)=>changeReport(event.target.value)} value={definition.key}>{catalog.map((item)=><option key={item.key} value={item.key}>{item.name}</option>)}</select></label>
        <label><span className="mb-1 block text-xs font-medium text-task-text-muted">From</span><input className="task-field" onChange={(event)=>changeFilter("from",event.target.value)} type="date" value={filters.from}/></label>
        <label><span className="mb-1 block text-xs font-medium text-task-text-muted">To</span><input className="task-field" onChange={(event)=>changeFilter("to",event.target.value)} type="date" value={filters.to}/></label>
        {canSelectBranch&&definition.filters.includes("branch_id")?<label><span className="mb-1 block text-xs font-medium text-task-text-muted">Branch context</span><select className="task-field" onChange={(event)=>{changeFilter("branch_id",event.target.value||undefined);changeFilter("department_id",undefined);}} value={filters.branch_id??""}><option value="">All authorized branches</option>{options.branches.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>:null}
        {elevated&&definition.filters.includes("department_id")?<label><span className="mb-1 block text-xs font-medium text-task-text-muted">Department context</span><select className="task-field" onChange={(event)=>changeFilter("department_id",event.target.value||undefined)} value={filters.department_id??""}><option value="">All authorized departments</option>{scopedDepartments.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>:null}
        <label><span className="mb-1 block text-xs font-medium text-task-text-muted">Status</span><input className="task-field" onChange={(event)=>changeFilter("status",event.target.value.toLowerCase().replace(/\s+/g,"_")||undefined)} placeholder="All" value={filters.status??""}/></label>
        <label><span className="mb-1 block text-xs font-medium text-task-text-muted">Rows per page</span><select className="task-field" onChange={(event)=>changeFilter("page_size",Number(event.target.value))} value={filters.page_size}>{[10,25,50,100].map((size)=><option key={size}>{size}</option>)}</select></label>
      </div>
      <p className="mt-3 text-xs text-task-text-muted">Active filters (URL-backed): Report = {definition.name} · Date = {filters.from} through {filters.to} · Branch = {filters.branch_id?"Selected authorized branch":"All authorized"} · Department = {filters.department_id?"Selected authorized department":"All authorized"} · Status = {filters.status?titleCase(filters.status):"All"} · Page = {filters.page}. Maximum date range: {definition.maxDateRangeDays} days.</p>
    </div>
    {loading?<LoadingPanels count={3}/>:error?<ErrorPanel message={error} onRetry={load}/>:data?<>
      <Panel title={definition.name} description={`${definition.description} ${data.total.toLocaleString("en-IN")} authorized row${data.total===1?"":"s"}.`}>
        {data.rows.length===0?<p className="py-10 text-center text-sm text-task-text-muted">No authorized rows match these filters.</p>:<><div className="hidden overflow-x-auto sm:block"><table className="w-full min-w-[56rem] text-left text-sm"><thead className="text-xs text-task-text-muted"><tr>{definition.columns.map((column)=><th className="pb-2 pr-4 font-medium" key={column.key}>{column.label}</th>)}</tr></thead><tbody>{data.rows.map((row,index)=><tr className="border-t border-task-border" key={String(row[definition.columns[0]!.key]??index)}>{definition.columns.map((column)=><td className="max-w-72 truncate py-3 pr-4" key={column.key}>{renderCell(row[column.key])}</td>)}</tr>)}</tbody></table></div><div className="grid gap-3 sm:hidden">{data.rows.map((row,index)=><article className="rounded-lg border border-task-border p-3" key={String(row[definition.columns[0]!.key]??index)}>{definition.columns.map((column)=><div className="flex justify-between gap-3 border-b border-task-border py-2 last:border-0" key={column.key}><span className="text-xs text-task-text-muted">{column.label}</span><span className="max-w-[60%] text-right text-sm font-medium">{renderCell(row[column.key])}</span></div>)}</article>)}</div></>}
        <div className="mt-4 flex items-center justify-between gap-3"><Button className="border-task-border bg-task-bg text-task-text hover:bg-task-muted" disabled={filters.page<=1} onClick={()=>changeFilter("page",filters.page-1)} variant="secondary">Previous</Button><span className="text-xs text-task-text-muted">Page {filters.page} of {totalPages}</span><Button className="border-task-border bg-task-bg text-task-text hover:bg-task-muted" disabled={filters.page>=totalPages} onClick={()=>changeFilter("page",filters.page+1)} variant="secondary">Next</Button></div>
      </Panel>
      <Panel className="mt-4" title="Export history" description="Private CSV files expire automatically; object paths and signed URLs are never displayed.">{!history?.rows.length?<p className="py-8 text-center text-sm text-task-text-muted">No exports in this date range.</p>:<div className="flex flex-col gap-2">{history.rows.map((row)=>{const status=String(row.status);return <div className="grid gap-2 rounded-lg border border-task-border p-3 text-sm sm:grid-cols-[minmax(9rem,1fr)_7rem_7rem_10rem_auto] sm:items-center" key={String(row.export_id)}><div><p className="font-medium">{titleCase(String(row.report_key))}</p><p className="text-xs text-task-text-muted">Requested {renderCell(row.requested_at)}</p></div><span className="inline-flex items-center gap-2"><StatusDot tone={status==="completed"?"success":status==="failed"||status==="cancelled"||status==="expired"?"danger":"warning"}/>{titleCase(status)}</span><span className="text-xs text-task-text-muted">{renderCell(row.progress_percent)}% · {renderCell(row.row_count)} rows</span><span className="text-xs text-task-text-muted">Expires {renderCell(row.expires_at)}</span><div className="flex gap-1 sm:justify-end">{status==="completed"?<button aria-label="Download export" className="flex size-10 items-center justify-center rounded-lg hover:bg-task-muted" onClick={()=>void lifecycle("download",String(row.export_id))} type="button"><Download className="size-4"/></button>:null}{status==="queued"||status==="processing"?<button aria-label="Cancel export" className="flex size-10 items-center justify-center rounded-lg hover:bg-task-muted" onClick={()=>void lifecycle("cancel",String(row.export_id))} type="button"><Square className="size-4"/></button>:null}{status==="failed"||status==="expired"?<button aria-label="Retry export" className="flex size-10 items-center justify-center rounded-lg hover:bg-task-muted" onClick={()=>void lifecycle("retry",String(row.export_id))} type="button"><RotateCcw className="size-4"/></button>:null}</div></div>;})}</div>}<Button className="mt-3 border-task-border bg-task-bg text-task-text hover:bg-task-muted" onClick={()=>void load()} variant="secondary"><RefreshCw/>Refresh history</Button></Panel>
    </>:null}
  </PageSurface>;
}
