"use client";
import {useEffect,useRef,useState} from "react";
import {INSIGHTS_RANGES,buildAttentionFindings,insightValue,type InsightsDetailPage,type InsightOption,classifyCrmVisitOutcome} from "@jewelos/core";
import Link from "@/next-shim/link";
import {useCrmRefresh} from "@/crm-port/use-crm-refresh";
import {fetchCrmInsights,fetchCrmInsightsOptions,fetchCrmInsightRecords,readCrmInsightsFilter,type CrmInsightsFilter,type CrmInsightsPayload,type CrmInsightsOptions} from "@/lib/crm-insights-api";
const tabs={visits:"Visits & Outcomes",followups:"Follow-ups",clients:"Clients & Leads",staff:"Staff & Branches"};
export function CrmInsightsDashboard(){
 const [filter,setFilter]=useState(()=>readCrmInsightsFilter(window.location.search));const [data,setData]=useState<CrmInsightsPayload|null>(null);const [loadedKey,setLoadedKey]=useState("");const [options,setOptions]=useState<CrmInsightsOptions|null>(null);const [loading,setLoading]=useState(false);const [allGroups,setAllGroups]=useState(false);const [error,setError]=useState("");const [selection,setSelection]=useState<{metric:string;group?:string|undefined;offset:number}|null>(()=>{const metric=new URLSearchParams(window.location.search).get("metric");return metric&&/^[a-z_]{1,50}$/.test(metric)?{metric,offset:0}:null;});const [page,setPage]=useState<InsightsDetailPage|null>(null);const [detailError,setDetailError]=useState("");const [detailLoading,setDetailLoading]=useState(false);const [from,setFrom]=useState(filter.from??"");const [to,setTo]=useState(filter.to??"");const generation=useRef(0);const detailGeneration=useRef(0);const close=useRef<HTMLButtonElement>(null);const key=JSON.stringify(filter);const visible=loadedKey===key?data:null;
 useEffect(()=>{setFrom(filter.from??"");setTo(filter.to??"");},[filter.from,filter.to]);
 const requestedBranch=new URLSearchParams(window.location.search).get("jewelos_branch_id");const [mappedBranch,setMappedBranch]=useState("");const mappingPending=!!requestedBranch&&mappedBranch!==requestedBranch;const [mappingError,setMappingError]=useState("");
 useEffect(()=>{if(!requestedBranch)return;let active=true;void fetchCrmInsightsOptions(filter).then(o=>{if(!active)return;const branch=o.branches.find(b=>b.jewelos_branch_id===requestedBranch);if(!branch){setMappingError("This JewelOS branch has no CRM mapping. Open CRM directly to select its own branch.");return;}setFilter(f=>({...f,branch_id:branch.id}));setOptions(o);setMappedBranch(requestedBranch);}).catch(()=>{if(active)setMappingError("CRM branch mapping could not load. Refresh to retry.");});return()=>{active=false;};},[requestedBranch]);
 const refresh=async()=>{const seq=++generation.current;setLoading(true);setError("");try{const result=await fetchCrmInsights(filter);if(seq===generation.current){setData(result);setLoadedKey(key);}}catch{if(seq===generation.current)setError("CRM analytics could not load. Check connection and access, then retry.");}finally{if(seq===generation.current)setLoading(false);}};
 useCrmRefresh(async()=>{if(!mappingPending)await refresh();});
 useEffect(()=>{if(mappingPending)return;void refresh();let active=true;void fetchCrmInsightsOptions(filter).then(o=>{if(active)setOptions(o);}).catch(()=>{if(active)setOptions(null);});return()=>{active=false;generation.current++;};},[key,mappingPending]);
 useEffect(()=>{const restore=()=>{setFilter(readCrmInsightsFilter(window.location.search));setSelection(null);};window.addEventListener("popstate",restore);return()=>window.removeEventListener("popstate",restore);},[]);
 useEffect(()=>{if(mappingPending)return;const seq=++detailGeneration.current;setPage(null);setDetailError("");if(!selection)return;setDetailLoading(true);void fetchCrmInsightRecords(filter,selection.metric,selection.group,selection.offset).then(p=>{if(seq===detailGeneration.current)setPage(p);}).catch(()=>{if(seq===detailGeneration.current)setDetailError("Could not load matching records. Close and retry.");}).finally(()=>{if(seq===detailGeneration.current)setDetailLoading(false);});return()=>{detailGeneration.current++;};},[selection,key,mappingPending]);
 useEffect(()=>{if(!selection)return;const previous=document.activeElement;close.current?.focus();return()=>{if(previous instanceof HTMLElement)previous.focus();};},[selection!==null]);
 const update=(f:CrmInsightsFilter)=>{const params=new URLSearchParams();for(const [k,v] of Object.entries(f))if(v!==undefined)params.set(k,String(v));window.history.pushState({},"",`${window.location.pathname}?${params}`);setSelection(null);setFilter(f);};
 const open=(metric:string,group?:string)=>setSelection({metric,group,offset:0});
 const select=(label:string,k:keyof CrmInsightsFilter,rows:InsightOption[])=> <label className="text-xs font-medium" key={k}>{label}<select aria-label={label} className="mt-1 min-h-11 w-full rounded-lg border bg-white p-2 text-sm" value={String(filter[k]??"")} onChange={e=>update({...filter,[k]:e.target.value||undefined})}><option value="">All</option>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>;
 const keys=filter.tab==="followups"?["open_followups","overdue_followups","due_soon_followups","aged_followups","completed_followup_updates"]:filter.tab==="clients"?["unique_clients","returning_clients","leads","converted_leads","lead_conversion_rate"]:["visits","purchases","purchase_rate","overdue_followups","unknown_outcomes"];
 const metrics=keys.flatMap(k=>{const m=visible?.metrics.find(x=>x.key===k);return m?[m]:[];});const findings=buildAttentionFindings(visible?.metrics??[]);const outcomeMax=Math.max(1,...(visible?.outcomes.map(o=>o.count)??[]));
 if(mappingPending)return <main className="p-5"><p role={mappingError?"alert":"status"}>{mappingError||"Resolving CRM branch scope..."}</p></main>;
 return <main className="mx-auto max-w-7xl space-y-5 px-4 py-6"><header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-stone-500">CRM insights</p><h1 className="mt-1 text-3xl font-semibold">Know your clients. Focus the next action.</h1><p className="mt-2 text-sm text-stone-600">Recorded visits, outcomes, leads, and follow-ups  -  with the records behind every number.</p>{visible?<p className="mt-2 text-xs text-stone-500">{visible.from} to {visible.to}  |  Updated {new Date(visible.generatedAt).toLocaleTimeString("en-IN",{timeZone:"Asia/Kolkata"})}</p>:null}</div><button className="min-h-11 rounded-lg border bg-white px-4 text-sm" disabled={loading} onClick={()=>void refresh()}>{loading?"Refreshing...":"Refresh"}</button></header>
 <nav aria-label="CRM analysis" className="flex gap-2 overflow-x-auto">{(Object.keys(tabs) as Array<keyof typeof tabs>).map(tab=><button key={tab} aria-pressed={filter.tab===tab} className={`min-h-11 shrink-0 rounded-full border px-4 text-sm ${filter.tab===tab?"bg-stone-800 text-white":"bg-white"}`} onClick={()=>update({...filter,tab,groupBy:tab==="clients"?"source":"branch",crm_name:undefined,event_type:undefined,buy_status:undefined,source_channel:undefined})}>{tabs[tab]}</button>)}</nav>
 <details className="rounded-xl border bg-white p-4"><summary className="min-h-11 cursor-pointer text-sm font-semibold">Filters  |  {INSIGHTS_RANGES.find(r=>r.id===filter.preset)?.name??"Selected period"}</summary><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-medium">Period<select aria-label="Period" className="mt-1 min-h-11 w-full rounded-lg border bg-white p-2" value={filter.preset} onChange={e=>{const day=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());setFrom(day);setTo(day);update({...filter,preset:e.target.value,...(e.target.value==="custom"?{from:day,to:day}:{from:undefined,to:undefined})});}}>{INSIGHTS_RANGES.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{filter.preset==="custom"?<><label className="text-xs">From<input aria-label="From" className="mt-1 min-h-11 w-full rounded-lg border p-2" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-xs">To<input aria-label="To" className="mt-1 min-h-11 w-full rounded-lg border p-2" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="min-h-11 rounded-lg border px-3 text-sm" onClick={()=>update({...filter,from,to})}>Apply dates</button></>:null}{options?<>{select("Branch","branch_id",options.branches)}{select(filter.tab==="followups"?"Entered by staff":"Salesperson / creator","salesperson_id",options.salespeople)}{filter.tab!=="followups"?<>{select("Recorded CRM name","crm_name",options.crm)}{select("Client's recorded lead source","source_channel",options.sources)}{filter.tab!=="clients"?<>{select("Visit type","event_type",options.visitTypes)}{select("Recorded outcome","buy_status",options.outcomes)}</>:null}</>:null}</>:null}<label className="text-xs font-medium">Compare by<select aria-label="Compare by" className="mt-1 min-h-11 w-full rounded-lg border p-2" value={filter.groupBy} onChange={e=>update({...filter,groupBy:e.target.value as CrmInsightsFilter["groupBy"]})}>{["branch","salesperson",...(filter.tab!=="followups"&&filter.tab!=="clients"?["crm","outcome"]:[]),...(filter.tab==="clients"?["source"]:[])].map(g=><option key={g} value={g}>{g}</option>)}</select></label><button className="min-h-11 rounded-lg border px-3 text-sm" onClick={()=>update({version:1,preset:"this_month",tab:filter.tab,groupBy:"branch"})}>Reset filters</button></div></details>
 {error?<div className="rounded-xl border bg-white p-4" role="alert"><p>{error}</p><button className="min-h-11" onClick={()=>void refresh()}>Retry</button></div>:null}{loading&&!visible?<p role="status">Loading CRM insights...</p>:null}
 <section className="grid grid-cols-2 gap-3 lg:grid-cols-5">{metrics.map(m=><button key={m.key} className="min-w-0 rounded-xl border bg-white p-4 text-left" onClick={()=>open(m.key)}><p className="text-xs text-stone-500">{m.label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{insightValue(m)}</p><p className="mt-2 text-xs text-stone-500">{m.basis==="current"?"As of refresh":"Selected period"}</p>{m.denominator!==null?<p className="text-xs">{m.numerator} / {m.denominator} eligible records</p>:null}{m.previous!==null?<p className="mt-1 text-xs text-stone-500">Previous period: {m.previous}</p>:null}<span className="mt-2 block text-xs font-medium text-amber-800">View records  &rarr;</span></button>)}</section>
 {visible?<><section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Needs attention</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{findings.map(f=><button key={f.id} className="min-h-11 rounded-lg border p-3 text-left" onClick={()=>open(f.metricKey)}><p className="text-sm font-semibold">{f.title}  &rarr;</p><p className="mt-1 text-xs text-stone-600">{f.description}</p></button>)}{!findings.length?<p className="text-sm text-stone-600">No attention flags in available CRM measures.</p>:null}</div></section>
 <section className="grid items-start gap-5 lg:grid-cols-2">{filter.tab==="visits"||filter.tab==="staff"?<><article className="rounded-xl border bg-white p-4"><h2 className="font-semibold">What happened during visits?</h2><p className="mt-1 text-xs text-stone-500">Each visit appears once under its exact saved outcome. Unknown outcomes remain visible.</p><div className="mt-4 space-y-3">{visible.outcomes.map(o=><button className="block min-h-11 w-full text-left" key={o.id} onClick={()=>{const next={...filter,groupBy:"outcome" as const};update(next);open("group_work",o.id);}}><div className="flex justify-between gap-3 text-sm"><span>{classifyCrmVisitOutcome(o.id).category}</span><span className="font-semibold">{o.count}</span></div><div className="mt-2 h-2 rounded bg-stone-100"><div className="h-full rounded bg-amber-700" style={{width:`${o.count/outcomeMax*100}%`}}/></div></button>)}</div></article><article className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Visits and recorded purchases over time</h2><p className="mt-1 text-xs text-stone-500">Visits / Purchase-positive visits. Long ranges use weekly buckets.</p><div className="mt-4 max-h-72 space-y-2 overflow-auto">{visible.trend.map(p=><div className="flex items-center gap-3 text-xs" key={p.date}><span className="shrink-0">{p.date}</span><div className="h-2 flex-1 rounded bg-stone-100"><div className="h-full rounded bg-amber-700" style={{width:`${p.due/Math.max(1,...visible.trend.map(x=>x.due))*100}%`}}/></div><span className="shrink-0 tabular-nums">{p.due} / {p.completed}</span></div>)}</div></article></>:null}
 <article className="rounded-xl border bg-white p-4 lg:col-span-2"><h2 className="font-semibold">Compare {filter.groupBy}</h2><p className="mt-1 text-xs text-stone-500">{visible.groupBasis}</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{(allGroups?visible.groups:visible.groups.slice(0,10)).map(g=><button key={g.id} className="min-h-11 rounded-lg border p-3 text-left" onClick={()=>open("group_work",g.id)}><p className="flex justify-between gap-3 text-sm font-medium"><span>{g.name}</span><span>{g.total}</span></p><p className="mt-2 text-xs text-stone-600">{filter.tab==="followups"?`${g.open} open  |  ${g.overdue} overdue`:filter.tab==="clients"?`${g.completed} linked conversions`:`${g.completed} purchase-positive visits`}</p></button>)}</div>{visible.groups.length>10?<button className="min-h-11 mt-3 text-sm" onClick={()=>setAllGroups(!allGroups)}>{allGroups?"Show top 10":"Show all groups"}</button>:null}</article></section>
 {filter.tab==="clients"?<p className="rounded-xl border bg-white p-4 text-sm text-stone-600">Client creation growth is unavailable: client records have no reliable creation timestamp. These cards show clients with recorded visits, returning visit identities, and leads created in the period.</p>:null}
 {filter.tab==="visits"?<details className="rounded-xl border bg-white p-4"><summary className="min-h-11 cursor-pointer text-sm font-medium">Recorded reasons for not buying</summary><p className="text-xs text-stone-500">A visit can have several saved reasons. Counts overlap and should not be summed as distinct visits. Free-text other reasons are omitted.</p>{visible.reasons?.map(r=><button key={r.id} className="flex min-h-11 w-full justify-between py-2 text-sm" onClick={()=>open("non_buying_reason",r.id)}><span>{r.name}</span><span>{r.count}</span></button>)}{!visible.reasons?.length?<p className="mt-3 text-sm">No structured reasons recorded in this scope.</p>:null}</details>:null}
 <details className="rounded-xl border bg-white p-4"><summary className="min-h-11 cursor-pointer text-sm font-medium">Additional CRM measures</summary><p className="text-xs text-stone-500">Purchase, order and repair indicators can overlap. Follow-up updates are saved history events; completion transitions use the existing done-status definition. A saved response is not proof of a call. Undated work is kept visible.</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{visible.metrics.filter(m=>!metrics.some(x=>x.key===m.key)).map(m=><button key={m.key} className="min-h-11 rounded-lg border p-3 text-left text-sm" onClick={()=>open(m.key)}>{m.label}: <strong>{insightValue(m)}</strong></button>)}</div></details>
 <details className="rounded-xl border bg-white p-4"><summary className="min-h-11 cursor-pointer text-sm font-medium">How to read these measures</summary><p className="text-xs leading-relaxed text-stone-600">Purchase-positive visits use saved purchase outcomes, including combined service-and-purchase visits. Exchanges, returns and orders without a purchase are separate outcomes. Missing outcomes are excluded from the purchase-rate denominator and shown separately. Visit status does not establish revenue or profit. Lead conversion uses explicit conversion links for leads created in the selected period. Current follow-up backlog includes older and undated work. Imported history may be incomplete; the dashboard does not infer missing attribution or outcomes.</p></details></>:null}
 {selection?<div className="fixed inset-0 z-50 flex justify-end bg-black/40"><section role="dialog" aria-modal="true" aria-label="CRM insight records" className="flex h-full w-full max-w-xl flex-col bg-white" onKeyDown={e=>{if(e.key==="Escape")setSelection(null);if(e.key==="Tab"){const nodes=e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),a[href]');const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><header className="flex justify-between border-b p-4"><h2>{selection.metric.replaceAll("_"," ")}  |  {page?.total??"..."}</h2><button ref={close} className="min-h-11 px-3" onClick={()=>setSelection(null)}>Close</button></header><div className="flex-1 space-y-3 overflow-auto p-4">{detailLoading?<p>Loading...</p>:null}{detailError?<p role="alert">{detailError}</p>:null}{page?.rows.map(r=><article className="rounded-lg border p-3" key={r.id}><p className="font-medium">{r.title}</p><p className="mt-1 text-xs text-stone-500">{r.status.replaceAll("_"," ")}  |  {r.due?new Date(r.due).toLocaleDateString("en-IN",{timeZone:"Asia/Kolkata"}):"No date"}</p>{r.client_id?<Link className="mt-2 inline-flex min-h-11 items-center text-sm text-amber-800" href={`/clients/${r.client_id}`}>Open client record  &rarr;</Link>:null}</article>)}</div><footer className="flex justify-between border-t p-4"><button className="min-h-11 px-3" disabled={!selection.offset||detailLoading} onClick={()=>setSelection({...selection,offset:Math.max(0,selection.offset-25)})}>Previous</button><button className="min-h-11 px-3" disabled={detailLoading||selection.offset+25>=(page?.total??0)} onClick={()=>setSelection({...selection,offset:selection.offset+25})}>Next</button></footer></section></div>:null}
 </main>;
}
