import {useEffect,useState} from "react";
import {INSIGHTS_RANGES,INSIGHTS_GROUPS,type InsightsFilter,type InsightsOptions,type InsightOption} from "@jewelos/core";
export function InsightsFilters({filter,options,onChange}:{filter:InsightsFilter;options:InsightsOptions|null;onChange:(f:InsightsFilter)=>void}){
 const [error,setError]=useState("");const [from,setFrom]=useState(filter.from??"");const [to,setTo]=useState(filter.to??"");
 useEffect(()=>{setFrom(filter.from??"");setTo(filter.to??"");},[filter.from,filter.to]);
 const change=(key:keyof InsightsFilter,value:string)=>{const next={...filter,[key]:value||undefined};if(key==="branch_id"){delete next.department_id;delete next.user_profile_id;}if(key==="department_id")delete next.user_profile_id;if(key==="flow_id")delete next.stage_id;try{onChange(next);setError("");}catch(e){setError(e instanceof Error?e.message:"Invalid filters");}};
 const select=(label:string,key:keyof InsightsFilter,rows:InsightOption[])=> <label className="min-w-0 text-xs font-medium" key={key}>{label}<select aria-label={label} className="task-field mt-1 min-h-11 w-full" value={String(filter[key]??"")} onChange={e=>change(key,e.target.value)}><option value="">All authorized</option>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>;
 return <details className="rounded-xl border border-task-border bg-task-bg p-4"><summary className="min-h-11 cursor-pointer text-sm font-semibold">Filters  |  {INSIGHTS_RANGES.find(r=>r.id===filter.preset)?.name}  |  {filter.groupBy.replaceAll("_"," ")}</summary><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-medium">Period<select className="task-field mt-1 min-h-11 w-full" aria-label="Period" value={filter.preset} onChange={e=>{if(e.target.value==="custom"){const day=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());setFrom(day);setTo(day);onChange({...filter,preset:"custom",from:day,to:day});}else onChange({...filter,preset:e.target.value,from:undefined,to:undefined});}}>{INSIGHTS_RANGES.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>
 <label className="text-xs font-medium">Compare by<select className="task-field mt-1 min-h-11 w-full" aria-label="Compare by" value={filter.groupBy} onChange={e=>change("groupBy",e.target.value)}>{INSIGHTS_GROUPS.map(g=><option key={g} value={g}>{g.replaceAll("_"," ")}</option>)}</select></label>
 {filter.preset==="custom"?<><label className="text-xs">From<input aria-label="From" className="task-field mt-1 min-h-11 w-full" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-xs">To<input aria-label="To" className="task-field mt-1 min-h-11 w-full" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="min-h-11 rounded-lg border border-task-border px-3 text-sm" onClick={()=>{try{onChange({...filter,from,to});setError("");}catch(e){setError(e instanceof Error?e.message:"Invalid dates");}}}>Apply dates</button></>:null}
 {options?<>{select("Branch","branch_id",options.branches)}{select("Department","department_id",options.departments)}{select("Current designation","designation_id",options.designations)}{select("Employee","user_profile_id",options.employees)}{filter.tab==="tasks"||filter.tab==="overview"?<>{select("Task type","task_type",options.taskTypes)}{select("Task category","category_id",options.categories)}{select("Source","source",options.sources)}{select("Priority","priority",["high","medium","low"].map(id=>({id,name:id})))}{select("Task status","status",["pending","in_progress","completed","rejected"].map(id=>({id,name:id.replaceAll("_"," ")})))}</>:null}{filter.tab==="workflows"?<>{select("Workflow version","flow_id",options.flows)}{select("Stage","stage_id",options.stages??[])}</>:null}</>:null}
 <button className="min-h-11 rounded-lg border border-task-border px-3 text-sm" onClick={()=>onChange({version:1,tab:filter.tab,preset:"this_month",groupBy:"department"})}>Reset filters</button></div>{error?<p role="alert" className="mt-3 text-sm text-task-overdue">{error}</p>:null}<p className="mt-3 text-xs text-task-text-muted">Filters narrow your authorized scope. Work filters apply to tasks; workflow filters apply to workflows.</p></details>;
}
