import {useCallback,useEffect,useMemo,useState,type ReactNode} from "react";
import {decodeInsightsSearch,buildAttentionFindings,INSIGHTS_TAB_LABELS,INSIGHTS_TABS,INSIGHTS_SECTIONS,type InsightsDetailFilter,type InsightMetric,type InsightsFilter} from "@jewelos/core";
import {fetchManagementInsights,fetchInsightsOptions} from "@jewelos/data/analytics/index";
import {useAuth} from "@/auth/AuthContext";
import {useTenantRealtimeRefresh} from "@/features/realtime/useTenantRealtimeRefresh";
import {useInsightsRequest,useInsightsState} from "./useInsightsState";
import {InsightsFilters} from "./InsightsFilters";
import {InsightsSummary} from "./InsightsSummary";
import {InsightsTrend,InsightsComparison} from "./InsightsCharts";
import {InsightsRecords} from "./InsightsRecords";
import {SavedViews} from "./SavedViews";
import {ErrorPanel,LoadingPanels,Panel} from "../components";
const INSIGHTS_TOPICS=["tasks","fms","forms","organization","settings"] as const;
export function ManagementDashboard({renderCrmSummary,crmAllowed=false}:{renderCrmSummary?:(filter:InsightsFilter)=>ReactNode;crmAllowed?:boolean}){
 const {profile}=useAuth();
 const {filter,update}=useInsightsState();const [sections,setSections]=useState([...INSIGHTS_SECTIONS]);const [selection,setSelection]=useState<InsightsDetailFilter|null>(()=>{const p=new URLSearchParams(window.location.search);const metricKey=p.get("metric");return metricKey&&/^[a-z_]{1,50}$/.test(metricKey)?{filter,metricKey,groupId:p.get("group")??undefined}:null;});const [copied,setCopied]=useState(false);
 const key=JSON.stringify(filter);const loader=useCallback(()=>fetchManagementInsights(filter),[key]);const optionLoader=useCallback(()=>fetchInsightsOptions(filter),[key]);const {data,error,loading,retry}=useInsightsRequest(loader,key);const options=useInsightsRequest(optionLoader,key);
 useTenantRealtimeRefresh({tenantId:profile?.tenant_id,topics:INSIGHTS_TOPICS,refresh:retry});
 useEffect(()=>{setSelection(s=>s&&JSON.stringify(s.filter)!==key?null:s);},[key]);
 useEffect(()=>{const restore=()=>{const p=new URLSearchParams(window.location.search);const metricKey=p.get("metric");setSelection(metricKey&&/^[a-z_]{1,50}$/.test(metricKey)?{filter:decodeInsightsSearch(window.location.search),metricKey,groupId:p.get("group")??undefined}:null);};window.addEventListener("popstate",restore);return()=>window.removeEventListener("popstate",restore);},[]);
 const closeRecords=()=>{const p=new URLSearchParams(window.location.search);p.delete("metric");p.delete("group");window.history.replaceState({},"",`${window.location.pathname}?${p}`);setSelection(null);};
 const open=useCallback((metricKey:string,groupId?:string)=>{const p=new URLSearchParams(window.location.search);p.set("metric",metricKey);if(groupId)p.set("group",groupId);else p.delete("group");window.history.pushState({},"",`${window.location.pathname}?${p}`);setSelection({filter,metricKey,groupId});},[filter]);
 const selected=useMemo(()=>{const keys=filter.tab==="overview"?["due","open","overdue","on_time_rate","active_stages","available_people"]:filter.tab==="tasks"?["due","cohort_completed","completion_rate","throughput","overdue","uncovered"]:filter.tab==="workflows"?["open_instances","active_stages","blocked_stages","pending_starters","review_forms","required_forms"]:filter.tab==="people"?["active_people","available_people","uncovered"]:[];return keys.flatMap(k=>{const m=data?.metrics.find(x=>x.key===k);return m?[m]:[];});},[data,filter.tab]);
 const findings=buildAttentionFindings(data?.metrics??[]);
 const currentModule=filter.tab==="workflows"?"workflows":filter.tab==="people"?"people":"tasks";
 const unavailable=data&&filter.tab!=="overview"&&filter.tab!=="crm"&&!data.moduleStates[currentModule];
 const content=(section:string)=>{
  if(section==="attention")return <Panel title="Needs attention" description="Evidence from your authorized scope. Suggestions open records; they never change work automatically."><div className="grid gap-3 sm:grid-cols-2">{findings.map(f=><button key={f.id} className="min-h-11 rounded-lg border border-task-border p-3 text-left hover:bg-task-muted" onClick={()=>open(f.metricKey)}><p className="text-sm font-semibold text-task-overdue">{f.title}  &rarr;</p><p className="mt-1 text-xs leading-relaxed text-task-text-muted">{f.description}</p></button>)}{!findings.length?<p className="text-sm text-task-text-muted">No attention flags in the available measures. This does not assess unrecorded work.</p>:null}</div></Panel>;
  if(section==="trend"&&data&&(filter.tab==="overview"||filter.tab==="tasks"))return <InsightsTrend points={data.trend} onOpen={()=>open("throughput")}/>;
  if(section==="comparison"&&data)return <InsightsComparison people={filter.tab==="people"} groups={data.groups} basis={data.groupBasis} onOpen={id=>open("group_work",id)}/>;
  if(section==="modules"&&data)return <Panel title="Explore operational detail"><div className="grid gap-2 sm:grid-cols-2">{INSIGHTS_TABS.filter(t=>t!=="overview"&&t!=="crm").map(t=><button className="min-h-11 rounded-lg border border-task-border p-3 text-left text-sm" key={t} onClick={()=>{setSelection(null);update({...filter,tab:t});}}>{INSIGHTS_TAB_LABELS[t]}  &rarr;</button>)}</div><p className="mt-3 text-xs text-task-text-muted">{data.missingDeadline} open work assignments have no recorded deadline. Availability reflects scheduling rules, not attendance or productivity.</p></Panel>;
  return null;
 };
 return <section className="-m-4 min-h-screen bg-task-muted p-4 text-task-text sm:-m-6 sm:p-6"><div className="mx-auto max-w-7xl space-y-5"><header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-task-text-muted">Management insights</p><h1 className="mt-1 font-display text-3xl">See what needs attention</h1><p className="mt-2 text-sm text-task-text-muted">Understand the evidence, compare teams, and inspect the work behind every number.</p>{data?<p className="mt-2 text-xs text-task-text-muted">{data.from} to {data.to}  |  {data.scopeLabel}  |  Updated {new Date(data.generatedAt).toLocaleTimeString("en-IN",{timeZone:data.timezone})}</p>:null}</div><div className="flex gap-2"><button className="min-h-11 rounded-lg border border-task-border bg-task-bg px-4 text-sm" onClick={()=>void navigator.clipboard?.writeText(window.location.href).then(()=>setCopied(true))}>{copied?"Link copied":"Copy view link"}</button><button className="min-h-11 rounded-lg bg-task-accent px-4 text-sm font-semibold text-task-bg" disabled={loading} onClick={()=>void retry()}>{loading?"Refreshing...":"Refresh"}</button></div></header>
 <nav aria-label="Dashboard analysis" className="flex gap-2 overflow-x-auto pb-1">{INSIGHTS_TABS.filter(t=>t!=="crm"||crmAllowed).map(t=><button className={`min-h-11 shrink-0 rounded-full px-4 text-sm ${filter.tab===t?"bg-task-accent font-semibold text-task-bg":"border border-task-border bg-task-bg"}`} key={t} aria-pressed={filter.tab===t} onClick={()=>{setSelection(null);update({...filter,tab:t});}}>{INSIGHTS_TAB_LABELS[t]}</button>)}</nav>
 <div className="grid items-start gap-3 lg:grid-cols-[2fr_1fr]"><InsightsFilters filter={filter} options={options.data} onChange={f=>{setSelection(null);update(f);}}/><SavedViews config={{version:1,filter,sections}} onApply={c=>{setSelection(null);setSections(c.sections);update(c.filter);}}/></div>{options.error?<p className="text-xs text-task-text-muted">Filter options unavailable. Refresh to retry.</p>:null}
 {filter.tab==="crm"?crmAllowed?renderCrmSummary?.(filter)??<Panel title="CRM summary"><p>CRM analytics are unavailable in this deployment.</p></Panel>:<Panel title="CRM access unavailable"><p>This view requires CRM access.</p></Panel>:<>{loading&&!data?<LoadingPanels count={6}/>:null}{error?<ErrorPanel message={error} onRetry={()=>void retry()}/>:null}{unavailable?<Panel title="Section unavailable"><p>Access or availability settings restrict this section.</p></Panel>:data?<><InsightsSummary metrics={selected as InsightMetric[]} onOpen={open}/><div className="grid items-start gap-5 lg:grid-cols-2">{sections.map(s=><div key={s} className={s==="attention"||s==="modules"?"lg:col-span-2":"min-w-0"}>{content(s)}</div>)}</div><details className="rounded-xl border border-task-border bg-task-bg p-4"><summary className="min-h-11 cursor-pointer text-sm font-medium">Metric definitions & additional measures</summary><p className="mb-4 text-xs text-task-text-muted">Due work is one effective-deadline cohort. Completion activity includes work from any due period. Current backlog includes older and undated open work. Rejected/cancelled work is excluded from open counts. Starter completion scope follows the current assignee organization; runtime stages retain recorded scope. Review age runs from submission time. Group totals can include both due-period and current open work.</p><InsightsSummary metrics={data.metrics.filter(m=>!selected.some(s=>s.key===m.key))} onOpen={open}/></details></>:null}</>}
 </div>{selection?<InsightsRecords selection={selection} onClose={closeRecords} onPage={offset=>setSelection({...selection,offset})}/>:null}</section>;
}
