import { useEffect, useState } from "react";
import { RefreshCw, RotateCcw } from "lucide-react";
import { Button, Notice } from "@/components/ui";
import { loadDeliveryLogs, retryDelivery } from "./api";
import type { DeliveryLog } from "./types";
import { deliveryCanRetry } from "./viewModel";

const displayDate = (value: string | null): string => value && !Number.isNaN(Date.parse(value)) ? new Date(value).toLocaleString() : "—";

export function DeliveryLogs() {
  const [logs,setLogs]=useState<DeliveryLog[]>([]); const [state,setState]=useState(""); const [channel,setChannel]=useState(""); const [eventType,setEventType]=useState(""); const [search,setSearch]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [retrying,setRetrying]=useState<string|null>(null);
  const refresh=async()=>{setLoading(true);setError(null);try{setLogs(await loadDeliveryLogs({state,channel,eventType,search}));}catch(caught){setError(caught instanceof Error?caught.message:"Delivery logs could not be loaded");}finally{setLoading(false);}};
  useEffect(()=>{void refresh();},[]);
  return <section><div className="mb-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><select aria-label="Delivery state" className="task-field" onChange={(event)=>setState(event.target.value)} value={state}><option value="">All states</option>{["pending","scheduled","processing","delivered","retry_wait","failed_terminal","blocked_configuration","cancelled"].map((value)=><option key={value} value={value}>{value}</option>)}</select><select aria-label="Delivery channel" className="task-field" onChange={(event)=>setChannel(event.target.value)} value={channel}><option value="">All channels</option>{["in_app","email","whatsapp","sms","push"].map((value)=><option key={value} value={value}>{value}</option>)}</select><input aria-label="Event type" className="task-field" onChange={(event)=>setEventType(event.target.value)} placeholder="Event type" value={eventType}/><input aria-label="Search delivery logs" className="task-field" onChange={(event)=>setSearch(event.target.value)} placeholder="Delivery ID or event" value={search}/><Button onClick={()=>void refresh()} variant="secondary"><RefreshCw className="size-4"/> Apply</Button></div>{loading?<div className="h-32 animate-pulse rounded-xl bg-task-muted"/>:error?<Notice tone="danger">{error}</Notice>:logs.length===0?<Notice tone="task">No delivery logs match these filters.</Notice>:<div className="overflow-x-auto rounded-xl border border-task-border"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-task-muted text-xs uppercase tracking-wider text-task-text-muted"><tr><th className="p-3">Event</th><th className="p-3">Recipient</th><th className="p-3">Channel</th><th className="p-3">State</th><th className="p-3">Attempts</th><th className="p-3">Safe error</th><th className="p-3">Created</th><th className="p-3">Action</th></tr></thead><tbody>{logs.map((log)=><tr className="border-t border-task-border bg-task-bg text-task-text" key={log.delivery_id}><td className="p-3 capitalize">{typeof log.event_type === "string" ? log.event_type.replaceAll("_"," ") : "system"}</td><td className="p-3 font-mono text-xs">{typeof log.recipient_label === "string" ? log.recipient_label : "—"}</td><td className="p-3">{typeof log.channel === "string" ? log.channel : "unknown"}</td><td className="p-3">{typeof log.state === "string" ? log.state : "unknown"}</td><td className="p-3">{log.attempt_count}/{log.max_attempts}</td><td className="p-3 text-task-text-muted">{log.error_category??"—"}</td><td className="p-3 text-xs">{displayDate(log.created_at)}</td><td className="p-3">{deliveryCanRetry(log.state)?<Button disabled={retrying===log.delivery_id} onClick={()=>{setRetrying(log.delivery_id);void retryDelivery(log.delivery_id).then(refresh).catch((caught:unknown)=>setError(caught instanceof Error?caught.message:"Retry failed")).finally(()=>setRetrying(null));}} variant="ghost"><RotateCcw className="size-4"/> Retry</Button>:"—"}</td></tr>)}</tbody></table></div>}</section>;
}
