import { useMemo, useState } from "react";
import { Archive, Plus, Save, Trash2 } from "lucide-react";
import { CONDITION_OPERATORS, EVENT_VARIABLES, NOTIFICATION_EVENT_TYPES, RECIPIENT_TYPES, type NotificationEventType, type RecipientRule } from "@jewelos/core";
import { Button, Modal, Notice } from "@/components/ui";
import { archiveRule, saveRule, setRuleEnabled } from "./api";
import type { NotificationRuleRow, NotificationTemplateRow, ProviderAvailability, RuleDraft } from "./types";
import { validateRuleDraft } from "./viewModel";

const roles = ["super_admin","admin","manager","hr","crm","staff","doer","housekeeping"];
const emptyRule: RuleDraft = { name: "", eventType: "task_assigned", conditions: [], recipients: [{ type: "assigned_users" }], channelTemplates: {}, delayMinutes: 0, cooldownMinutes: 0, maxAttempts: 3, backoffMinutes: 5, priority: "medium", enabled: true };
function asArray(value: unknown): Array<Record<string, unknown>> { return Array.isArray(value) ? value.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === "object")) : []; }
function asObject(value: unknown): Record<string, string> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string,string> : {}; }

export function RuleManager({ rules, templates, providers, profiles, onRefresh }: { rules: readonly NotificationRuleRow[]; templates: readonly NotificationTemplateRow[]; providers: readonly ProviderAvailability[]; profiles: readonly { id: string; employee_name: string; user_role: string }[]; onRefresh: () => Promise<void> }) {
  const [draft,setDraft]=useState<RuleDraft|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  const availableChannels=useMemo(()=>new Set(providers.filter((provider)=>provider.is_available).map((provider)=>provider.channel)),[providers]);
  const edit=(rule:NotificationRuleRow)=>setDraft({id:rule.id,name:rule.name,eventType:rule.event_type,conditions:asArray(rule.conditions).map((item)=>({field:String(item.field??""),operator:String(item.operator??"equals"),...(item.value===undefined?{}:{value:String(item.value)})})),recipients:asArray(rule.recipient_rules).map((item)=>({type:String(item.type) as RecipientRule["type"],...(Array.isArray(item.user_ids)?{userIds:item.user_ids.map(String)}:{}),...(typeof item.role==="string"?{role:item.role}:{})})),channelTemplates:asObject(rule.channel_templates),delayMinutes:rule.delay_minutes,cooldownMinutes:rule.cooldown_minutes,maxAttempts:rule.max_attempts,backoffMinutes:rule.backoff_minutes,priority:rule.priority,enabled:rule.is_active??false});
  const errors=draft?validateRuleDraft(draft):[];
  const submit=async()=>{if(!draft||errors.length)return;setBusy(true);setError(null);try{await saveRule(draft);setDraft(null);await onRefresh();}catch(caught){setError(caught instanceof Error?caught.message:"Rule could not be saved");}finally{setBusy(false);}};
  const updateRecipient=(type:string)=>{if(!draft)return;const recipient:RecipientRule=type==="specified_users"?{type:"specified_users",userIds:[]}:type==="specified_role"?{type:"specified_role",role:"manager"}:{type:type as RecipientRule["type"]};setDraft({...draft,recipients:[recipient]});};
  const currentRecipient=draft?.recipients[0];
  const eligibleTemplates=draft?templates.filter((template)=>template.event_type===draft.eventType&&template.lifecycle==="active"&&template.is_active&&availableChannels.has(template.channel)):[];
  return <section><div className="mb-4 flex justify-end"><Button onClick={()=>setDraft(emptyRule)}><Plus className="size-4"/> New rule</Button></div><div className="space-y-3">{rules.map((rule)=><article className="rounded-xl border border-task-border bg-task-bg p-4" key={rule.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-task-text">{rule.name}</h3><p className="mt-1 text-xs capitalize text-task-text-muted">{rule.event_type.replaceAll("_"," ")} · {Object.keys(asObject(rule.channel_templates)).join(", ")||"No channel"}</p></div><button aria-label={`${rule.is_active?"Disable":"Enable"} ${rule.name}`} className={rule.is_active?"rounded-full bg-success/10 px-3 py-1 text-xs text-success":"rounded-full bg-task-muted px-3 py-1 text-xs text-task-text-muted"} disabled={rule.lifecycle==="archived"} onClick={()=>void setRuleEnabled(rule.id,!rule.is_active).then(onRefresh)} type="button">{rule.is_active?"Enabled":"Disabled"}</button></div><div className="mt-4 flex gap-2"><Button onClick={()=>edit(rule)} variant="secondary">Edit</Button>{rule.lifecycle==="active"?<Button onClick={()=>void archiveRule(rule.id).then(onRefresh).catch((caught:unknown)=>setError(caught instanceof Error?caught.message:"Archive failed"))} variant="ghost"><Archive className="size-4"/> Archive</Button>:null}</div></article>)}</div>{rules.length===0?<Notice tone="task">No notification rules have been configured.</Notice>:null}{error?<div className="mt-4"><Notice tone="danger">{error}</Notice></div>:null}
  {draft?<Modal onClose={()=>setDraft(null)} title={draft.id?"Edit notification rule":"New notification rule"} tone="light" wide><div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="label text-task-text-muted">Name</span><input className="task-field" onChange={(event)=>setDraft({...draft,name:event.target.value})} value={draft.name}/></label><label><span className="label text-task-text-muted">Event</span><select className="task-field" onChange={(event)=>setDraft({...draft,eventType:event.target.value as NotificationEventType,conditions:[],channelTemplates:{}})} value={draft.eventType}>{NOTIFICATION_EVENT_TYPES.map((event)=><option key={event} value={event}>{event.replaceAll("_"," ")}</option>)}</select></label><label><span className="label text-task-text-muted">Recipient resolution</span><select className="task-field" onChange={(event)=>updateRecipient(event.target.value)} value={currentRecipient?.type}>{RECIPIENT_TYPES.map((type)=><option key={type} value={type}>{type.replaceAll("_"," ")}</option>)}</select></label>
  {currentRecipient?.type==="specified_users"?<label className="sm:col-span-2"><span className="label text-task-text-muted">Active users</span><select className="task-field min-h-28" multiple onChange={(event)=>setDraft({...draft,recipients:[{type:"specified_users",userIds:[...event.target.selectedOptions].map((option)=>option.value)}]})} value={[...(currentRecipient.userIds??[])]}>{profiles.map((profile)=><option key={profile.id} value={profile.id}>{profile.employee_name} · {profile.user_role}</option>)}</select></label>:null}
  {currentRecipient?.type==="specified_role"?<label className="sm:col-span-2"><span className="label text-task-text-muted">Active role in event scope</span><select className="task-field" onChange={(event)=>setDraft({...draft,recipients:[{type:"specified_role",role:event.target.value}]})} value={currentRecipient.role}>{roles.map((role)=><option key={role} value={role}>{role.replaceAll("_"," ")}</option>)}</select></label>:null}
  <div className="sm:col-span-2"><div className="mb-2 flex items-center justify-between"><span className="label text-task-text-muted">Conditions · all must match</span><Button onClick={()=>setDraft({...draft,conditions:[...draft.conditions,{field:EVENT_VARIABLES[draft.eventType][0]??"",operator:"equals",value:""}]})} variant="secondary"><Plus className="size-3"/> Add</Button></div><div className="space-y-2">{draft.conditions.map((condition,index)=><div className="grid gap-2 sm:grid-cols-[1fr_1fr_1fr_auto]" key={`${condition.field}-${index}`}><select className="task-field" onChange={(event)=>setDraft({...draft,conditions:draft.conditions.map((item,i)=>i===index?{...item,field:event.target.value}:item)})} value={condition.field}>{EVENT_VARIABLES[draft.eventType].map((field)=><option key={field} value={field}>{field}</option>)}</select><select className="task-field" onChange={(event)=>setDraft({...draft,conditions:draft.conditions.map((item,i)=>i===index?{...item,operator:event.target.value}:item)})} value={condition.operator}>{CONDITION_OPERATORS.map((operator)=><option key={operator} value={operator}>{operator}</option>)}</select><input className="task-field" disabled={["is_empty","is_not_empty","is_today","is_past","is_future"].includes(condition.operator)} onChange={(event)=>setDraft({...draft,conditions:draft.conditions.map((item,i)=>i===index?{...item,value:event.target.value}:item)})} value={condition.value??""}/><Button aria-label="Remove condition" onClick={()=>setDraft({...draft,conditions:draft.conditions.filter((_,i)=>i!==index)})} variant="ghost"><Trash2 className="size-4"/></Button></div>)}</div></div>
  <label className="sm:col-span-2"><span className="label text-task-text-muted">Channel and template</span><select className="task-field" onChange={(event)=>{const template=templates.find((item)=>item.id===event.target.value);setDraft({...draft,channelTemplates:template?{[template.channel]:template.id}:{}})}} value={Object.values(draft.channelTemplates)[0]??""}><option value="">Select an available template</option>{eligibleTemplates.map((template)=><option key={template.id} value={template.id}>{template.channel} · {template.name}</option>)}</select><p className="mt-1 text-xs text-task-text-muted">External channels stay disabled until provider availability is confirmed by the server.</p></label>
  {([['Delay minutes','delayMinutes'],['Cooldown minutes','cooldownMinutes'],['Max attempts','maxAttempts'],['Backoff minutes','backoffMinutes']] as const).map(([label,key])=><label key={key}><span className="label text-task-text-muted">{label}</span><input className="task-field" min={key==='maxAttempts'||key==='backoffMinutes'?1:0} onChange={(event)=>setDraft({...draft,[key]:Number(event.target.value)})} type="number" value={draft[key]}/></label>)}<label><span className="label text-task-text-muted">Priority</span><select className="task-field" onChange={(event)=>setDraft({...draft,priority:event.target.value as RuleDraft['priority']})} value={draft.priority}>{["high","medium","low"].map((value)=><option key={value} value={value}>{value}</option>)}</select></label><label className="flex items-center gap-2 pt-6"><input checked={draft.enabled} onChange={(event)=>setDraft({...draft,enabled:event.target.checked})} type="checkbox"/> Enable after save</label></div>{errors.length?<div className="mt-4"><Notice tone="danger">{errors.join(" · ")}</Notice></div>:null}<div className="mt-5 flex justify-end gap-2"><Button onClick={()=>setDraft(null)} variant="secondary">Cancel</Button><Button disabled={busy||errors.length>0||!draft.name.trim()} onClick={()=>void submit()}><Save className="size-4"/> Save rule</Button></div></Modal>:null}</section>;
}
