import type { ReportColumn, ReportDefinition } from "./types";
import type { UserRole } from "../roleMenu";

const ALL: readonly UserRole[] = ["super_admin","admin","manager","hr","crm","staff","doer","housekeeping"];
const OPS: readonly UserRole[] = ["super_admin","admin","manager","staff","doer","housekeeping","crm"];
const CRM: readonly UserRole[] = ["super_admin","admin","manager","crm"];
const PEOPLE: readonly UserRole[] = ["super_admin","admin","manager","hr"];
const ADMIN: readonly UserRole[] = ["super_admin","admin"];
const c = (key: string, label: string, sensitive = false): ReportColumn => ({ key, label, ...(sensitive ? { sensitive: true } : {}) });
const report = (definition: ReportDefinition) => definition;

export const REPORT_CATALOG: readonly ReportDefinition[] = [
  report({key:"task_operations",name:"Task operations",description:"Assigned task status, priority, due time, and checklist progress.",roles:OPS,filters:["from","to","branch_id","department_id","status","user_profile_id","page","page_size"],columns:[c("task_id","Task ID"),c("title","Task"),c("task_type","Type"),c("priority","Priority"),c("status","Status"),c("planned_datetime","Due"),c("assignee_name","Assignee",true),c("checklist_completion","Checklist")],defaultSort:"planned_datetime asc, task_id asc",maxDateRangeDays:90,exportEligible:true}),
  report({key:"task_completion_delay",name:"Task completion and delay",description:"Transparent completion timing with on-time and delay measures.",roles:OPS,filters:["from","to","branch_id","department_id","user_profile_id","page","page_size"],columns:[c("task_id","Task ID"),c("title","Task"),c("assignee_name","Assignee",true),c("planned_datetime","Due"),c("actual_datetime","Completed"),c("on_time","On time"),c("delay_minutes","Delay (minutes)")],defaultSort:"actual_datetime desc, task_id asc",maxDateRangeDays:366,exportEligible:true}),
  report({key:"fms_instances_stages",name:"FMS instances and stages",description:"Flow instance and stage state in authorized scope.",roles:OPS,filters:["from","to","branch_id","department_id","status","user_profile_id","page","page_size"],columns:[c("instance_id","Instance ID"),c("reference_number","Reference"),c("flow_name","Flow"),c("instance_status","Instance status"),c("stage_name","Stage"),c("stage_status","Stage status"),c("planned_datetime","Planned"),c("assignee_name","Assignee",true)],defaultSort:"planned_datetime asc, instance_id asc",maxDateRangeDays:180,exportEligible:true}),
  report({key:"fms_sla",name:"FMS SLA",description:"Planned versus actual stage timing and breach state.",roles:OPS,filters:["from","to","branch_id","department_id","status","user_profile_id","page","page_size"],columns:[c("instance_id","Instance ID"),c("reference_number","Reference"),c("stage_name","Stage"),c("planned_datetime","Planned"),c("actual_datetime","Completed"),c("sla_state","SLA state"),c("delay_minutes","Delay (minutes)")],defaultSort:"planned_datetime asc, instance_id asc",maxDateRangeDays:366,exportEligible:true}),
  report({key:"form_submissions_reviews",name:"Form submissions and reviews",description:"Submission and review metadata without form answers.",roles:["super_admin","admin","manager","crm","staff"],filters:["from","to","branch_id","department_id","status","user_profile_id","page","page_size"],columns:[c("submission_id","Submission ID"),c("form_name","Form"),c("status","Review status"),c("submitted_at","Submitted"),c("submitted_by_name","Submitted by",true),c("reviewed_at","Reviewed"),c("reviewed_by_name","Reviewed by",true)],defaultSort:"submitted_at desc, submission_id asc",maxDateRangeDays:366,exportEligible:true}),
  report({key:"crm_clients_ownership",name:"CRM clients and ownership",description:"Client record identifiers, branch, owner, status, and completeness only.",roles:CRM,filters:["from","to","branch_id","status","user_profile_id","page","page_size"],columns:[c("client_id","Client ID"),c("branch_name","Branch"),c("owner_name","CRM owner",true),c("status","Status"),c("created_at","Created"),c("profile_complete","Profile complete")],defaultSort:"created_at desc, client_id asc",maxDateRangeDays:366,exportEligible:true}),
  report({key:"crm_walkins",name:"CRM walk-ins",description:"Authorized visit activity without contact details or document paths.",roles:CRM,filters:["from","to","branch_id","user_profile_id","page","page_size"],columns:[c("walkin_id","Walk-in ID"),c("client_id","Client ID"),c("branch_name","Branch"),c("visit_date","Visit date"),c("crm_owner_name","CRM owner",true),c("buy_status","Visit outcome")],defaultSort:"visit_date desc, walkin_id asc",maxDateRangeDays:180,exportEligible:true}),
  report({key:"crm_interactions",name:"CRM interactions",description:"Authorized interaction metadata without contact details.",roles:CRM,filters:["from","to","branch_id","status","user_profile_id","page","page_size"],columns:[c("interaction_id","Interaction ID"),c("client_id","Client ID"),c("event_type","Type"),c("subject","Subject"),c("outcome","Outcome"),c("occurred_at","Occurred"),c("actor_name","Recorded by",true)],defaultSort:"occurred_at desc, interaction_id asc",maxDateRangeDays:180,exportEligible:true}),
  report({key:"crm_followups",name:"CRM follow-ups",description:"Authorized follow-up scheduling and lifecycle state.",roles:CRM,filters:["from","to","branch_id","status","user_profile_id","page","page_size"],columns:[c("followup_id","Follow-up ID"),c("client_id","Client ID"),c("subject","Subject"),c("due_date","Due"),c("status","Status"),c("assignee_name","Assignee",true),c("completed_at","Completed")],defaultSort:"due_date asc, followup_id asc",maxDateRangeDays:180,exportEligible:true}),
  report({key:"people_availability",name:"People availability",description:"Authorized working status and daily availability.",roles:PEOPLE,filters:["from","to","branch_id","department_id","status","user_profile_id","page","page_size"],columns:[c("profile_id","Profile ID"),c("employee_name","Employee",true),c("branch_name","Branch"),c("department_name","Department"),c("working_status","Working status"),c("date","Date"),c("availability_status","Availability")],defaultSort:"date desc, profile_id asc",maxDateRangeDays:90,exportEligible:true}),
  report({key:"people_task_performance",name:"People task performance",description:"Separate per-person task counts and timing; no ranking or composite score.",roles:PEOPLE,filters:["from","to","branch_id","department_id","user_profile_id","page","page_size"],columns:[c("profile_id","Profile ID"),c("employee_name","Employee",true),c("tasks_assigned","Assigned"),c("tasks_completed","Completed"),c("completion_rate","Completion rate"),c("on_time_completed","On-time completed"),c("overdue_open","Overdue open"),c("average_delay_minutes","Average delay")],defaultSort:"employee_name asc, profile_id asc",maxDateRangeDays:366,exportEligible:true}),
  report({key:"notification_delivery_health",name:"Notification delivery health",description:"Aggregate delivery state and retry health without message bodies or provider payloads.",roles:ADMIN,filters:["from","to","status","page","page_size"],columns:[c("channel","Channel"),c("status","Status"),c("delivery_count","Deliveries"),c("retry_count","Retries"),c("latest_attempt_at","Latest attempt")],defaultSort:"channel asc, status asc",maxDateRangeDays:90,exportEligible:true}),
  report({key:"export_history",name:"Export history",description:"Authorized export request lifecycle and retention metadata.",roles:ALL,filters:["from","to","status","user_profile_id","page","page_size"],columns:[c("export_id","Export ID"),c("report_key","Report"),c("status","Status"),c("progress_percent","Progress"),c("row_count","Rows"),c("requested_at","Requested"),c("expires_at","Expires"),c("requester_name","Requested by",true)],defaultSort:"requested_at desc, export_id asc",maxDateRangeDays:366,exportEligible:false}),
];

export function reportFor(key: string): ReportDefinition | undefined { return REPORT_CATALOG.find((item) => item.key === key); }
export function reportsForRole(role: UserRole): readonly ReportDefinition[] { return REPORT_CATALOG.filter((item) => item.roles.includes(role)); }
export function canExportReport(role: UserRole, key: string): boolean { const item = reportFor(key); return Boolean(item?.exportEligible && item.roles.includes(role)); }
