import { useEffect, useMemo, useState } from "react";
import { AlignLeft, Banknote, CalendarDays, CheckSquare, ChevronDown, ChevronUp, CircleDot, Eye, FileUp, Hash, ListChecks, Mail, Minus, Pencil, Phone, Plus, Star, Trash2, Type } from "lucide-react";
import { normalizeFormDefinition, validateFormDefinition, type FormFieldDefinition, type FormTemplateDefinition, type Json, type UserRole } from "@jewelos/core";
import { Button, Field, Modal, Notice } from "@/components/ui";
import { loadMasterOptions, type MasterOption } from "@/features/dropdowns/api";
import { saveDraft, savePublishedForm, type FormBundle } from "./api";
import { FormRenderer, type DynamicOptions } from "./FormRenderer";

const ROLES: UserRole[] = ["super_admin", "admin", "manager", "hr", "crm", "staff", "doer", "housekeeping"];
const OPTION_TYPES = new Set<FormFieldDefinition["type"]>(["select", "multiselect", "radio"]);
const NUMBER_TYPES = new Set<FormFieldDefinition["type"]>(["number", "currency", "rating"]);
const TEXT_TYPES = new Set<FormFieldDefinition["type"]>(["text", "textarea"]);
const FIELD_KINDS = [
  { type: "text", label: "Short Text", icon: Type }, { type: "textarea", label: "Long Text", icon: AlignLeft }, { type: "date", label: "Date Picker", icon: CalendarDays }, { type: "select", label: "Dropdown", icon: ChevronDown },
  { type: "checkbox", label: "Checkbox", icon: CheckSquare }, { type: "radio", label: "Radio Group", icon: CircleDot }, { type: "file", label: "File Upload", icon: FileUp }, { type: "rating", label: "Rating", icon: Star },
  { type: "multiselect", label: "Multi-select", icon: ListChecks }, { type: "divider", label: "Divider", icon: Minus }, { type: "email", label: "Email", icon: Mail }, { type: "phone", label: "Phone", icon: Phone },
  { type: "currency", label: "Currency", icon: Banknote }, { type: "section_header", label: "Section", icon: Type }, { type: "number", label: "Number", icon: Hash },
] as const;
type FieldKind = (typeof FIELD_KINDS)[number];
const fieldLabel = (type: FormFieldDefinition["type"]) => FIELD_KINDS.find((item) => item.type === type)?.label ?? type.replaceAll("_", " ");
const fieldIcon = (type: FormFieldDefinition["type"]) => FIELD_KINDS.find((item) => item.type === type)?.icon ?? Type;
const newField = (type: FormFieldDefinition["type"], sortOrder: number): FormFieldDefinition => ({ key: "field_" + (sortOrder + 1), label: fieldLabel(type), type, sortOrder, required: false, shown: true, editable: true, ...(OPTION_TYPES.has(type) ? { options: ["Option 1", "Option 2"] } : {}) });
const initial = (bundle?: FormBundle): FormTemplateDefinition => ({ name: bundle?.name ?? "", description: bundle?.description ?? "", fields: (bundle?.fields ?? []).map(({ condition: _condition, ...field }) => field), permissions: { roles: ((bundle?.permissions as { roles?: UserRole[] } | null)?.roles) ?? ["staff"] } });
const toDraftFields = (fields: readonly FormFieldDefinition[]) => fields.map(({ id: _id, sortOrder: _sortOrder, condition: _condition, ...field }) => field);

export function FormBuilder({ bundle, dynamicOptions, onClose, onSaved }: { bundle?: FormBundle | undefined; dynamicOptions: DynamicOptions; onClose: () => void; onSaved: () => Promise<void> }) {
  const [form, setForm] = useState(() => initial(bundle)); const [saving, setSaving] = useState(false); const [preview, setPreview] = useState(false); const [error, setError] = useState<string | null>(null); const [masterOptions, setMasterOptions] = useState<MasterOption[]>([]); const [editing, setEditing] = useState<number | null>(null);
  const baseline = useMemo(() => JSON.stringify(normalizeFormDefinition(initial(bundle))), [bundle]); const dirty = JSON.stringify(normalizeFormDefinition(form)) !== baseline; const issues = useMemo(() => validateFormDefinition(normalizeFormDefinition(form)), [form]);
  useEffect(() => { void loadMasterOptions([], true).then(setMasterOptions).catch(() => setMasterOptions([])); }, []);
  useEffect(() => { const handler = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", handler); return () => window.removeEventListener("beforeunload", handler); }, [dirty]);
  const add = (type: FieldKind["type"]) => setForm((current) => { const next = [...current.fields, newField(type, current.fields.length)]; setEditing(next.length - 1); return { ...current, fields: next }; });
  const patchField = (index: number, patch: Partial<FormFieldDefinition>) => setForm((current) => ({ ...current, fields: current.fields.map((field, position) => position === index ? { ...field, ...patch, sortOrder: position } : field) }));
  const move = (index: number, direction: number) => setForm((current) => { const next = [...current.fields]; const target = index + direction; if (target < 0 || target >= next.length) return current; [next[index], next[target]] = [next[target]!, next[index]!]; setEditing(target); return { ...current, fields: next.map((field, position) => ({ ...field, sortOrder: position })) }; });
  const remove = (index: number) => setForm((current) => { setEditing((selected) => selected === index ? null : selected !== null && selected > index ? selected - 1 : selected); return { ...current, fields: current.fields.filter((_, position) => position !== index).map((field, position) => ({ ...field, sortOrder: position })) }; });
  const save = async () => { if (issues.length) { setError(issues[0]?.message ?? "Fix the highlighted form settings before saving."); return; } setSaving(true); setError(null); try { const normalized = normalizeFormDefinition(form); const payload = { name: normalized.name, description: normalized.description ?? "", permissions: { roles: normalized.permissions?.roles ?? [] } } as unknown as Json; const fields = toDraftFields(normalized.fields) as unknown as Json; if (bundle?.lifecycle === "published") await savePublishedForm(bundle.id, payload, fields); else await saveDraft(bundle?.id ?? null, payload, fields); await onSaved(); onClose(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save the form."); } finally { setSaving(false); } };
  return <div className="space-y-5">{error ? <Notice tone="danger">{error}</Notice> : null}<section className="rounded-xl border border-gold/20 p-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Form name"><input className="field" onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} placeholder="e.g. Walk-in Form" value={form.name} /></Field><Field label="Description"><input className="field" onChange={(event) => setForm((current) => ({ ...current, description: event.target.value }))} placeholder="What is this form for?" value={form.description ?? ""} /></Field></div><details className="mt-3"><summary className="cursor-pointer text-xs font-medium text-soft-grey">Who can use this form</summary><div className="mt-2 flex flex-wrap gap-x-4 gap-y-2">{ROLES.map((role) => <label className="text-xs text-champagne" key={role}><input checked={form.permissions?.roles.includes(role) ?? false} onChange={(event) => setForm((current) => ({ ...current, permissions: { roles: event.target.checked ? [...new Set([...(current.permissions?.roles ?? []), role])] : (current.permissions?.roles ?? []).filter((value) => value !== role) } }))} type="checkbox" /> {role}</label>)}</div></details></section>
    <section aria-label="Add fields"><div className="mb-3 flex items-center gap-2"><span className="grid size-7 place-items-center rounded-full bg-gold text-obsidian"><Plus className="size-4" /></span><h3 className="text-xl font-semibold text-gold">Add fields</h3></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">{FIELD_KINDS.map((kind) => <FieldPaletteButton key={kind.type} kind={kind} onAdd={add} />)}</div><p className="mt-2 text-xs text-soft-grey">Conditions are intentionally not available; every added question is shown normally.</p></section>
    <section aria-label="Fields"><div className="mb-3 flex items-center justify-between gap-3"><div className="flex items-center gap-2"><ListChecks className="size-5 text-gold" /><h3 className="text-xl font-semibold text-gold">Fields</h3></div><span className="rounded-full bg-gold/10 px-3 py-1 text-xs font-semibold text-gold">{form.fields.length} added</span></div>{form.fields.length === 0 ? <Notice>Add a field above to begin your form.</Notice> : <div className="space-y-2">{form.fields.map((field, index) => <CompactFieldRow editing={editing === index} field={field} index={index} key={field.key + "-" + index} masterOptions={masterOptions} onEdit={() => setEditing((current) => current === index ? null : index)} onMove={move} onPatch={patchField} onRemove={remove} />)}</div>}</section>
    <div className="flex flex-wrap justify-end gap-2 border-t border-gold/15 pt-4"><Button onClick={() => setPreview(true)} type="button" variant="secondary"><Eye />Preview</Button><Button disabled={saving} onClick={() => void save()}>{saving ? "Saving..." : bundle?.lifecycle === "published" ? "Save changes" : "Save draft"}</Button><Button onClick={() => { if (!dirty || window.confirm("Discard unsaved form changes?")) onClose(); }} type="button" variant="ghost">Cancel</Button></div>{preview ? <Modal onClose={() => setPreview(false)} title="Form preview" wide><FormRenderer definition={normalizeFormDefinition(form)} dynamicOptions={dynamicOptions} preview /></Modal> : null}</div>;
}
function FieldPaletteButton({ kind, onAdd }: { kind: FieldKind; onAdd: (type: FieldKind["type"]) => void }) { const Icon = kind.icon; return <button className="flex min-h-24 flex-col items-center justify-center gap-2 rounded-xl border border-gold/20 bg-charcoal/40 px-2 text-center text-sm font-semibold text-champagne transition hover:border-gold hover:bg-gold/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold" onClick={() => onAdd(kind.type)} type="button"><span className="grid size-9 place-items-center rounded-full bg-gold/10 text-gold"><Icon className="size-5" /></span>{kind.label}</button>; }
function CompactFieldRow({ field, index, editing, masterOptions, onEdit, onPatch, onMove, onRemove }: { field: FormFieldDefinition; index: number; editing: boolean; masterOptions: MasterOption[]; onEdit: () => void; onPatch: (index: number, patch: Partial<FormFieldDefinition>) => void; onMove: (index: number, direction: number) => void; onRemove: (index: number) => void }) { const Icon = fieldIcon(field.type); return <article className="overflow-hidden rounded-xl border border-gold/20 bg-charcoal/30"><div className="flex items-center gap-2 p-2 sm:p-3"><div className="flex flex-col"><button aria-label="Move field up" className="text-soft-grey hover:text-gold disabled:opacity-30" disabled={index === 0} onClick={() => onMove(index, -1)} type="button"><ChevronUp className="size-4" /></button><button aria-label="Move field down" className="text-soft-grey hover:text-gold" onClick={() => onMove(index, 1)} type="button"><ChevronDown className="size-4" /></button></div><span className="grid size-8 place-items-center rounded-full bg-gold/10 text-gold"><Icon className="size-4" /></span><button className="min-w-0 flex-1 text-left" onClick={onEdit} type="button"><span className="block truncate font-semibold text-champagne">{field.label || fieldLabel(field.type)}</span><span className="text-xs text-soft-grey">{fieldLabel(field.type)}{field.required ? " · required" : ""}</span></button><Button aria-label="Edit field" className="size-9 min-h-9 p-0" onClick={onEdit} type="button" variant="ghost"><Pencil className="size-4" /></Button><Button aria-label="Remove field" className="size-9 min-h-9 p-0" onClick={() => onRemove(index)} type="button" variant="danger"><Trash2 className="size-4" /></Button></div>{editing ? <FieldEditor field={field} index={index} masterOptions={masterOptions} onPatch={onPatch} /> : null}</article>; }
function FieldEditor({ field, index, masterOptions, onPatch }: { field: FormFieldDefinition; index: number; masterOptions: MasterOption[]; onPatch: (index: number, patch: Partial<FormFieldDefinition>) => void }) { const validation = field.validation ?? {}; const categories = [...new Set(masterOptions.map((item) => item.master_type))].sort(); const updateValidation = (key: "min" | "max" | "minLength" | "maxLength", raw: string) => onPatch(index, { validation: { ...validation, [key]: raw === "" ? undefined : Number(raw) } }); return <div className="grid gap-3 border-t border-gold/15 p-3 sm:grid-cols-2"><Field label="Question"><input className="field" onChange={(event) => onPatch(index, { label: event.target.value })} value={field.label} /></Field><Field label="Internal key"><input className="field" onChange={(event) => onPatch(index, { key: event.target.value.toLowerCase().replace(/[^a-z0-9_]/g, "_") })} value={field.key} /></Field><Field label="Placeholder"><input className="field" onChange={(event) => onPatch(index, { placeholder: event.target.value })} value={field.placeholder ?? ""} /></Field><Field label="Helper text"><input className="field" onChange={(event) => onPatch(index, { helperText: event.target.value })} value={field.helperText ?? ""} /></Field>{OPTION_TYPES.has(field.type) ? <OptionSource categories={categories} field={field} index={index} masterOptions={masterOptions} onPatch={onPatch} /> : null}{NUMBER_TYPES.has(field.type) ? <><Field label="Minimum"><input className="field" onChange={(event) => updateValidation("min", event.target.value)} type="number" value={validation.min ?? ""} /></Field><Field label="Maximum"><input className="field" onChange={(event) => updateValidation("max", event.target.value)} type="number" value={validation.max ?? ""} /></Field></> : null}{TEXT_TYPES.has(field.type) ? <><Field label="Minimum length"><input className="field" onChange={(event) => updateValidation("minLength", event.target.value)} type="number" value={validation.minLength ?? ""} /></Field><Field label="Maximum length"><input className="field" onChange={(event) => updateValidation("maxLength", event.target.value)} type="number" value={validation.maxLength ?? ""} /></Field></> : null}<div className="flex flex-wrap items-center gap-4 sm:col-span-2"><label className="text-sm text-champagne"><input checked={field.required === true} onChange={(event) => onPatch(index, { required: event.target.checked })} type="checkbox" /> Required</label><label className="text-sm text-champagne"><input checked={field.shown !== false} onChange={(event) => onPatch(index, { shown: event.target.checked })} type="checkbox" /> Shown</label><label className="text-sm text-champagne"><input checked={field.editable !== false} onChange={(event) => onPatch(index, { editable: event.target.checked })} type="checkbox" /> Editable</label></div></div>; }
function OptionSource({ field, index, categories, masterOptions, onPatch }: { field: FormFieldDefinition; index: number; categories: string[]; masterOptions: MasterOption[]; onPatch: (index: number, patch: Partial<FormFieldDefinition>) => void }) { const [source, setSource] = useState("local"); return <div className="space-y-2 sm:col-span-2"><Field label="Choice source"><select className="field" onChange={(event) => setSource(event.target.value)} value={source}><option value="local">Form-only options</option><option value="master">Dropdown Master category</option></select></Field>{source === "local" ? <Field label="Options (one per line)"><textarea className="field" onChange={(event) => onPatch(index, { options: event.target.value.split("\n").map((item) => item.trim()).filter(Boolean) })} value={(field.options ?? []).join("\n")} /></Field> : <Field label="Dropdown Master category"><select className="field" defaultValue="" onChange={(event) => onPatch(index, { options: masterOptions.filter((item) => item.master_type === event.target.value).map((item) => item.label) })}><option disabled value="">Choose a category</option>{categories.map((category) => <option key={category} value={category}>{category}</option>)}</select></Field>}</div>; }
