import {parseInsightsPayload,parseInsightsDetailPage,type InsightsPayload,type InsightOption} from "@jewelos/core";
import {crmSupabase} from "@/crm-port/runtime";
export type CrmInsightsFilter={version:1;preset:string;from?:string|undefined;to?:string|undefined;tab:"visits"|"followups"|"clients"|"staff";groupBy:"branch"|"salesperson"|"crm"|"outcome"|"source";branch_id?:string|undefined;salesperson_id?:string|undefined;crm_name?:string|undefined;source_channel?:string|undefined;event_type?:string|undefined;buy_status?:string|undefined};
export type CrmInsightsPayload=InsightsPayload&{outcomes:Array<{id:string;name:string;count:number}>;reasons?:Array<{id:string;name:string;count:number}>};
export type CrmInsightsOptions={branches:Array<InsightOption&{jewelos_branch_id?:string|null}>;salespeople:InsightOption[];crm:InsightOption[];sources:InsightOption[];outcomes:InsightOption[];visitTypes:InsightOption[]};
export const crmInsightsDefaults:CrmInsightsFilter={version:1,preset:"this_month",tab:"visits",groupBy:"branch"};
export function readCrmInsightsFilter(search:string):CrmInsightsFilter {const p=new URLSearchParams(search);const result={...crmInsightsDefaults};for(const k of ["preset","from","to","branch_id","salesperson_id","crm_name","source_channel","event_type","buy_status"] as const){const v=p.get(k);if(v&&v.length<=150)result[k]=v;}const tab=p.get("tab");if(tab==="followups"||tab==="clients"||tab==="staff")result.tab=tab;const group=p.get("groupBy");if(group==="salesperson"||group==="crm"||group==="outcome"||group==="source")result.groupBy=group;return result;}
export async function fetchCrmInsights(filter:CrmInsightsFilter):Promise<CrmInsightsPayload>{const {data,error}=await crmSupabase().rpc("get_crm_insights_v1",{p_context:filter});if(error)throw error;const base=parseInsightsPayload(data);if(!data||typeof data!=="object"||Array.isArray(data)||!Array.isArray(data.outcomes)||!data.outcomes.every(o=>o&&typeof o==="object"&&!Array.isArray(o)&&typeof o.id==="string"&&typeof o.name==="string"&&typeof o.count==="number"))throw new Error("Invalid visit outcomes");if(data.reasons!==undefined&&(!Array.isArray(data.reasons)||!data.reasons.every(o=>o&&typeof o==="object"&&!Array.isArray(o)&&typeof o.id==="string"&&typeof o.name==="string"&&typeof o.count==="number")))throw new Error("Invalid CRM reason totals");return {...base,outcomes:data.outcomes as CrmInsightsPayload["outcomes"],reasons:(data.reasons??[]) as NonNullable<CrmInsightsPayload["reasons"]>};}
export async function fetchCrmInsightsOptions(filter:CrmInsightsFilter):Promise<CrmInsightsOptions>{const {data,error}=await crmSupabase().rpc("get_crm_insights_options_v1",{p_context:filter});if(error)throw error;if(!data||typeof data!=="object"||Array.isArray(data)||!["branches","salespeople","crm","sources","outcomes","visitTypes"].every(k=>Array.isArray(data[k])&&(data[k] as unknown[]).every(x=>!!x&&typeof x==="object"&&"id" in x&&typeof x.id==="string"&&"name" in x&&typeof x.name==="string")))throw new Error("Invalid CRM options");return data as CrmInsightsOptions;}
export async function fetchCrmInsightRecords(filter:CrmInsightsFilter,metric:string,group?:string,offset=0){const {data,error}=await crmSupabase().rpc("get_crm_insight_records_v1",{p_context:filter,p_metric:metric,...(group?{p_group_id:group}:{}),p_offset:offset,p_limit:25});if(error)throw error;return parseInsightsDetailPage(data);}
