import { useCallback, useDeferredValue, useEffect, useRef, useState } from "react";
import { Plus, Store, UsersRound } from "lucide-react";
import { useAuth } from "@/auth/AuthContext";
import { Button, Modal, Notice } from "@/components/ui";
import { ClientDetail } from "@/features/crm/ClientDetail";
import { ClientForm } from "@/features/crm/ClientForm";
import { CrmDirectory, EMPTY_FILTERS } from "@/features/crm/CrmDirectory";
import { FollowupsPanel } from "@/features/crm/FollowupsPanel";
import { MergeDialog } from "@/features/crm/MergeDialog";
import { WalkinForm } from "@/features/crm/WalkinForm";
import { loadClient, loadCrmOptions, searchClients } from "@/features/crm/api";
import type { CrmClientDetail, CrmClientSummary, CrmOptions } from "@/features/crm/types";

const EMPTY_OPTIONS: CrmOptions={branches:[],profiles:[],dropdowns:[]};
export function CRMPage(){const{profile}=useAuth();const[section,setSection]=useState<"directory"|"followups">("directory");const[filters,setFilters]=useState(EMPTY_FILTERS);const deferredQuery=useDeferredValue(filters.query);const[items,setItems]=useState<CrmClientSummary[]>([]);const[options,setOptions]=useState<CrmOptions>(EMPTY_OPTIONS);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[detail,setDetail]=useState<CrmClientDetail|null>(null);const[modal,setModal]=useState<"new"|"edit"|"walkin"|"merge"|null>(null);const[success,setSuccess]=useState<string|null>(null);const requestSequence=useRef(0);const cursor=items.at(-1)?.next_cursor;
 const search=useCallback(async(append=false)=>{const sequence=++requestSequence.current;setLoading(true);setError(null);try{const result=await searchClients({...filters,query:deferredQuery,cursor:append?cursor:undefined,limit:25});if(sequence!==requestSequence.current)return;setItems((current)=>append?[...current,...result]:result);}catch(caught){if(sequence===requestSequence.current)setError(caught instanceof Error?caught.message:"Client search failed");}finally{if(sequence===requestSequence.current)setLoading(false);}},[cursor,deferredQuery,filters]);
 useEffect(()=>{void loadCrmOptions().then(setOptions).catch((caught)=>setError(caught instanceof Error?caught.message:"CRM options failed"));},[]);useEffect(()=>{const timer=window.setTimeout(()=>void search(false),250);return()=>window.clearTimeout(timer);},[deferredQuery,filters.branch_id,filters.assigned_crm_id,filters.client_type_id,filters.source_id,filters.potential_category,filters.followup_status]);
 const open=useCallback(async(id:string)=>{setLoading(true);setError(null);try{setDetail(await loadClient(id));}catch(caught){setError(caught instanceof Error?caught.message:"Client detail failed");}finally{setLoading(false);}},[]);const refreshDetail=useCallback(async()=>{if(detail)setDetail(await loadClient(detail.client.id));},[detail]);if(!profile)return null;
 return <><section className="mx-auto max-w-7xl space-y-5"><header className="rounded-2xl border border-task-border bg-task-bg p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><UsersRound className="size-6 text-task-accent"/><h1 className="text-2xl font-bold text-task-text">CRM</h1></div><p className="mt-1 text-sm text-task-text-muted">Authorized client relationships, visits, history, follow-ups, and private documents.</p></div><div className="flex flex-wrap gap-2"><Button onClick={()=>setModal("walkin")}><Store className="size-4"/>New walk-in</Button><Button onClick={()=>setModal("new")} variant="secondary"><Plus className="size-4"/>New client</Button></div></div></header>{success?<Notice tone="success">{success}</Notice>:null}{detail?<ClientDetail detail={detail} onBack={()=>setDetail(null)} onEdit={()=>setModal("edit")} onMerge={()=>setModal("merge")} onRefresh={refreshDetail} options={options}/>:<><nav className="flex gap-2 rounded-xl border border-task-border bg-task-bg p-2"><Button onClick={()=>setSection("directory")} variant={section==="directory"?"primary":"secondary"}>Client directory</Button><Button onClick={()=>setSection("followups")} variant={section==="followups"?"primary":"secondary"}>Follow-ups</Button></nav>{section==="directory"?<CrmDirectory error={error} filters={filters} hasMore={items.length>0&&items.length%25===0} items={items} loading={loading} onFilters={setFilters} onMore={()=>void search(true)} onOpen={(id)=>void open(id)} options={options}/>:<FollowupsPanel onOpenClient={(id)=>void open(id)} options={options}/>}</>}</section>{modal==="new"?<Modal onClose={()=>setModal(null)} title="New client" wide><ClientForm onCancel={()=>setModal(null)} onSaved={async(id)=>{setModal(null);setSuccess("Client created.");await search(false);await open(id);}} options={options}/></Modal>:null}{modal==="edit"&&detail?<Modal onClose={()=>setModal(null)} title="Edit client" wide><ClientForm client={detail.client} onCancel={()=>setModal(null)} onSaved={async()=>{setModal(null);setSuccess("Client updated.");await refreshDetail();}} options={options}/></Modal>:null}{modal==="walkin"?<Modal onClose={()=>setModal(null)} title="New walk-in" wide><WalkinForm onCancel={()=>setModal(null)} onSaved={async(id,summary)=>{setModal(null);setSuccess(summary);await search(false);await open(id);}} options={options}/></Modal>:null}{modal==="merge"&&detail?<MergeDialog onClose={()=>setModal(null)} onMerged={async()=>{setModal(null);setSuccess("Duplicate merged into the surviving client with history preserved.");await refreshDetail();}} survivor={detail}/>:null}</>;
}
