import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, GitBranch, Layers3, Pencil, Play, Plus, Search, Trash2 } from "lucide-react";
import { useAuth } from "@/auth/AuthContext";
import { Button, Notice } from "@/components/ui";
import { loadFmsBuilderData, deleteFmsFlow, type FmsData, type FmsFlowRow } from "@/features/fms/api";
import { FmsFlowBuilder } from "@/features/fms/FmsFlowBuilder";
import { FMSTasksPage } from "./FMSTasksPage";

export function FMSBuilderPage() {
  const { profile } = useAuth(); const canBuild = !!profile && ["super_admin", "admin", "manager"].includes(profile.user_role);
  const [view, setView] = useState<"live" | "library">("live"); const [data, setData] = useState<FmsData>(); const [error, setError] = useState<string | null>(null); const [query, setQuery] = useState(""); const [edit, setEdit] = useState<FmsFlowRow | null | undefined>();
  const refresh = useCallback(async () => { try { setError(null); setData(await loadFmsBuilderData()); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load FMS"); } }, []); useEffect(() => { void refresh(); }, [refresh]);
  const flows = useMemo(() => (data?.flows ?? []).filter((flow) => flow.status !== "archived" && `${flow.name} ${flow.description ?? ""}`.toLowerCase().includes(query.toLowerCase())), [data, query]);
  if (edit !== undefined && data) return <section><header className="mb-5 flex justify-between"><Button onClick={() => setEdit(undefined)} variant="ghost"><ArrowLeft className="size-4" />Back to FMS</Button></header><FmsFlowBuilder data={data} flow={edit} onClose={() => setEdit(undefined)} onSaved={refresh} /></section>;
  return <section className="mx-auto w-full max-w-7xl space-y-5"><header className="flex items-center justify-between rounded-3xl border border-gold/30 bg-gold/15 p-6"><div className="flex items-center gap-3"><GitBranch className="size-7 text-gold" /><div><h1 className="text-2xl font-semibold text-white">FMS Builder</h1><p className="text-sm text-soft-grey">Build workflows; users start them through the process form.</p></div></div>{canBuild ? <Button onClick={() => { setView("library"); setEdit(null); }}><Plus className="size-4" />New workflow</Button> : null}</header><label className="relative block"><Search className="absolute left-4 top-1/2 size-5 -translate-y-1/2 text-soft-grey" /><input className="field min-h-14 rounded-2xl pl-12" onChange={(event) => setQuery(event.target.value)} placeholder="Search workflows or tasks..." value={query} /></label><div className="grid grid-cols-2 gap-2 rounded-2xl border border-gold/20 bg-charcoal/50 p-1.5"><button className={view === "library" ? "rounded-xl bg-gold p-3 text-sm font-semibold text-obsidian" : "rounded-xl p-3 text-sm font-semibold text-champagne"} onClick={() => setView("library")} type="button"><Layers3 className="mr-2 inline size-4" />Flow library</button><button className={view === "live" ? "rounded-xl bg-gold p-3 text-sm font-semibold text-obsidian" : "rounded-xl p-3 text-sm font-semibold text-champagne"} onClick={() => setView("live")} type="button"><Play className="mr-2 inline size-4" />My workflow tasks</button></div>{view === "live" ? <FMSTasksPage query={query} /> : error ? <Notice tone="danger">{error}</Notice> : !canBuild ? <Notice>Workflow creation is available to authorized managers.</Notice> : !data ? <div className="h-48 animate-pulse rounded-2xl bg-charcoal" /> : <div className="grid gap-4">{flows.map((flow) => <article className="rounded-2xl border border-gold/20 bg-charcoal p-5" key={flow.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold text-white">{flow.name}</h2><p className="mt-1 text-sm text-soft-grey">{flow.description || "No description added."}</p><p className="mt-2 text-xs text-soft-grey">{flow.status} · v{flow.version} · used {flow.usage_count} times</p></div><div className="flex items-center gap-2">{flow.status === "draft" ? <Button onClick={() => setEdit(flow)} variant="secondary"><Pencil className="size-4" />Edit draft</Button> : <Notice>Published workflows run from their process form.</Notice>}<Button variant="danger" onClick={async () => { if (confirm("Are you sure you want to delete this workflow?")) { try { await deleteFmsFlow(flow.id); await refresh(); } catch (e) { alert(e instanceof Error ? e.message : "Failed to delete workflow"); } } }}><Trash2 className="size-4" /></Button></div></div></article>)}</div>}</section>;
}
