import { useCallback, useEffect, useMemo, useState } from "react";
import * as XLSX from "xlsx";
import { Download, Upload } from "lucide-react";
import type { TaskImportDraftRow, TaskImportIdentityRequirement } from "@jewelos/core";
import { Button, Notice } from "@/components/ui";
import { beginCurrentSheetTaskImport, commitCurrentSheetTaskImportChunk, loadTaskImportBatches, loadTaskImportIdentityCandidates, submitTaskBulkImport, validateTaskBulkImport, type TaskImportBatch, type TaskImportIdentityCandidate, type TaskImportValidation } from "@/features/tasks/import/api";
import { runTaskImportChunks } from "@/features/tasks/import/chunkRunner";
import { createCorrectionReportCsv } from "@/features/tasks/import/correctionReport";
import { applyIdentityMappings } from "@/features/tasks/import/identityMappings";
import { createTaskImportTemplate, hashTaskImportPayload, parseTaskImportFile, type TaskBulkImportIssue, type TaskBulkImportPayload } from "@/features/tasks/import/workbook";

function downloadBlob(contents: BlobPart, name: string, type: string) { const url=URL.createObjectURL(new Blob([contents],{type})); const anchor=document.createElement("a"); anchor.href=url; anchor.download=name; anchor.click(); URL.revokeObjectURL(url); }
async function hashRows(rows: readonly unknown[]) { const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(rows))); return [...new Uint8Array(digest)].map((item)=>item.toString(16).padStart(2,"0")).join(""); }

export function TaskBulkImportPage({ onBack }: { onBack: () => void }) {
  const [payload,setPayload]=useState<TaskBulkImportPayload|null>(null); const [draftRows,setDraftRows]=useState<readonly TaskImportDraftRow[]>([]); const [requirements,setRequirements]=useState<readonly TaskImportIdentityRequirement[]>([]); const [mappings,setMappings]=useState<Record<string,string>>({}); const [candidates,setCandidates]=useState<TaskImportIdentityCandidate[]>([]); const [issues,setIssues]=useState<readonly TaskBulkImportIssue[]>([]); const [fileLabel,setFileLabel]=useState(""); const [error,setError]=useState<string|null>(null); const [validation,setValidation]=useState<TaskImportValidation|null>(null); const [history,setHistory]=useState<TaskImportBatch[]>([]); const [busy,setBusy]=useState(false); const [progress,setProgress]=useState(0); const [result,setResult]=useState<string|null>(null);
  const refreshHistory=useCallback(async()=>{try{setHistory(await loadTaskImportBatches());}catch(caught){setError(caught instanceof Error?caught.message:"Unable to load import history");}},[]);
  useEffect(()=>{void refreshHistory(); void loadTaskImportIdentityCandidates().then(setCandidates).catch(()=>setCandidates([]));},[refreshHistory]);
  const mapped=useMemo(()=>applyIdentityMappings(draftRows,mappings),[draftRows,mappings]); const allIssues=useMemo(()=>[...issues,...mapped.issues],[issues,mapped.issues]); const readyRows=allIssues.length===0?mapped.rows:[];
  const download=()=>{const bytes=XLSX.write(createTaskImportTemplate(),{bookType:"xlsx",type:"array"}); downloadBlob(bytes,"mk-jewels-task-bulk-import.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");};
  const upload=async(file?:File)=>{if(!file)return;setBusy(true);setError(null);setResult(null);setValidation(null);setPayload(null);setDraftRows([]);setRequirements([]);setMappings({});setProgress(0);try{const parsed=await parseTaskImportFile(file);setFileLabel(file.name.replace(/[^A-Za-z0-9._ -]/g,"_"));setIssues(parsed.issues);if(parsed.sourceFormat==="mk_daily_checklist_csv"){setDraftRows(parsed.draftRows);setRequirements(parsed.identityRequirements);}else if(parsed.payload)setPayload(parsed.payload);else setError(parsed.errors.join(" "));}catch(caught){setError(caught instanceof Error?caught.message:"Unable to read file");}finally{setBusy(false);}};
  const validateCanonical=async()=>{if(!payload)return;setBusy(true);setError(null);try{setValidation(await validateTaskBulkImport(payload,await hashTaskImportPayload(payload)));}catch(caught){setError(caught instanceof Error?caught.message:"Validation failed");}finally{setBusy(false);}};
  const importCanonical=async()=>{if(!payload||!validation?.valid)return;setBusy(true);setError(null);try{const outcome=await submitTaskBulkImport(payload,validation.canonical_hash,fileLabel||"task-import.xlsx");setResult(`${outcome.created_count} tasks imported.`);setPayload(null);setValidation(null);await refreshHistory();}catch(caught){setError(caught instanceof Error?caught.message:"Import failed");}finally{setBusy(false);}};
  const importCurrentSheet=async()=>{if(!readyRows.length)return;setBusy(true);setError(null);setResult(null);try{const started=await beginCurrentSheetTaskImport(await hashRows(readyRows),fileLabel||"task-import.csv",readyRows.length);if(started.replayed&&started.outcome!=="in_progress"&&started.outcome!=="partial"){setResult(`This exact import already finished with outcome: ${started.outcome}.`);return;}const outcome=await runTaskImportChunks(started.batch_id,readyRows,(batch,rows)=>commitCurrentSheetTaskImportChunk(batch,rows as typeof readyRows),(done)=>setProgress(done));setResult(`${outcome.created} created, ${outcome.rejected} rejected, ${outcome.replayed} replayed. Outcome: ${outcome.outcome}.`);await refreshHistory();}catch(caught){setError(caught instanceof Error?caught.message:"Import failed");}finally{setBusy(false);}};
  const correction=()=>downloadBlob(createCorrectionReportCsv(allIssues),"task-import-corrections.csv","text/csv;charset=utf-8");
  return <section className="-m-4 min-h-[calc(100dvh-7.875rem)] bg-task-bg p-4 text-task-text sm:-m-6 sm:p-6"><div className="mx-auto max-w-6xl space-y-5"><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold">Task Bulk Import</h1><p className="mt-1 text-sm text-task-text-muted">One upload routes one-time work to Tasks and schedules to Recurring / To-Do.</p></div><div className="flex gap-2"><Button onClick={onBack} variant="secondary">Back to tasks</Button><Button onClick={download}><Download className="size-4"/>Download format</Button></div></header><Notice tone="task">Accepts the current 18-column CSV and the canonical workbook. Maximum 2 MiB and 2,500 rows. Blank source cells are never filled down. Imports run in resumable 100-row chunks and the server rechecks authorization.</Notice>{error?<Notice tone="danger">{error}</Notice>:null}{result?<Notice tone="success">{result}</Notice>:null}<div className="rounded-xl border border-task-border bg-task-bg p-4"><label className="label">Workbook or current checklist CSV</label><input accept=".xlsx,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv" className="task-field mt-1" onChange={(event)=>void upload(event.target.files?.[0])} type="file"/>{draftRows.length?<div className="mt-3 flex flex-wrap gap-2"><Button disabled={!readyRows.length||busy} onClick={()=>void importCurrentSheet()}><Upload className="size-4"/>{busy?`Importing ${progress}/${readyRows.length}…`:`Import ${readyRows.length} rows`}</Button>{allIssues.length?<Button onClick={correction} variant="secondary"><Download className="size-4"/>Correction report</Button>:null}</div>:null}{payload?<div className="mt-3 flex gap-2"><Button disabled={busy} onClick={()=>void validateCanonical()} variant="secondary">Validate workbook</Button><Button disabled={!validation?.valid||busy} onClick={()=>void importCanonical()}>Import workbook</Button></div>:null}</div>
  {requirements.length?<div className="rounded-xl border border-task-border p-4"><h2 className="font-semibold">Confirm identity mappings</h2><p className="mt-1 text-sm text-task-text-muted">Names are never matched automatically. Select the exact active account for every missing employee email and verifier.</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{requirements.map((requirement)=><label className="text-sm" key={requirement.key}><span className="label">{requirement.kind==="assignee"?"Employee":"Verifier"}: {requirement.label} (rows {requirement.source_rows.join(", ")})</span><select className="task-field mt-1" onChange={(event)=>setMappings((current)=>({...current,[requirement.key]:event.target.value}))} value={mappings[requirement.key]??""}><option value="">Select exact account</option>{candidates.map((candidate)=><option key={candidate.id} value={candidate.id}>{candidate.employee_name} — {candidate.email}</option>)}</select></label>)}</div></div>:null}
  {allIssues.length?<div className="rounded-xl border border-danger/30 p-4"><h2 className="font-semibold">Corrections required ({allIssues.length})</h2><div className="mt-3 max-h-80 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>Row</th><th>Field</th><th>Reason</th><th>Correction</th></tr></thead><tbody>{allIssues.slice(0,500).map((item,index)=><tr className="border-t border-task-border" key={`${item.row}-${item.field}-${index}`}><td>{item.row}</td><td>{item.field}</td><td>{item.reason}</td><td>{item.guidance}</td></tr>)}</tbody></table></div>{allIssues.length>500?<p className="mt-2 text-sm text-task-text-muted">Showing the first 500. Download the correction report for all rows.</p>:null}</div>:draftRows.length?<Notice tone="success">All rows and explicit identity mappings are ready for server validation and import.</Notice>:null}
  {validation?<div className="rounded-xl border border-task-border p-4"><h2 className="font-semibold">Canonical workbook validation</h2><p className="text-sm text-task-text-muted">{validation.summary.requested_count} requested · {validation.summary.error_count} errors</p></div>:null}<div className="rounded-xl border border-task-border p-4"><h2 className="font-semibold">Recent imports</h2>{history.length?<div className="mt-3 space-y-2">{history.map((batch)=><div className="rounded-lg bg-task-muted p-3 text-sm" key={batch.id}>{new Date(batch.created_at).toLocaleString("en-IN")} · {batch.safe_file_label??"Import"} · {batch.requested_count} requested / {batch.valid_count} created / {batch.error_count} rejected · {batch.outcome}</div>)}</div>:<p className="mt-2 text-sm text-task-text-muted">No recent imports visible to this account.</p>}</div></div></section>;
}
